"""Buying a condominium in Thailand as a foreigner: foreign quota, funds and transfer."""

C = {}

C['en'] = dict(
    title="Buying a Condo in Thailand as a Foreigner: Foreign Quota & Transfer | Walailak Law Firm",
    description="Legal support for foreigners buying a Thai condominium: the 49% foreign quota, remitting funds, due diligence, contract review and Land Office transfer.",
    eyebrow="CONDOMINIUM PURCHASE",
    h1="Buying a Condominium in Thailand as a Foreigner",
    lead="English-language legal support for foreign buyers of resale and new condominium units, from the first offer to registration at the Land Office, whether you are in Thailand or abroad.",
    introEyebrow="Foreign buyers",
    introTitle="Freehold is possible, but only inside the foreign quota",
    intro="Foreigners can own a condominium unit freehold in their own name, but only within the foreign quota: the Condominium Act limits foreign ownership to 49 per cent of the total area of a registered building, and the purchase money must be brought in from abroad in foreign currency and documented by the bank. A building whose quota is already used, a seller with a mortgage, unpaid common-area fees or a deposit paid too early can all turn a simple purchase into a problem. Walailak Law Firm checks the unit, the quota, the seller and the paperwork before you commit, reviews the reservation and sale agreements, and attends the transfer for you where needed. For projects that are still being built, see our off-plan contract review.",
    situations=["A resale condominium in Pattaya, Jomtien, Rayong or elsewhere, before you pay a deposit",
                "A reservation agreement or deposit requested before you have seen the title",
                "A cash buyer who will remit funds from abroad",
                "A buyer who will sign remotely through a power of attorney",
                "A seller that is a company, or a unit that is still mortgaged",
                "A foreign buyer with a Thai partner who is deciding how title should be held"],
    reviewTitle="What we check before you buy",
    reviewIntro="We work through the unit, the building and the paperwork in the order that protects your money.",
    cards=[("Foreign quota", "Whether foreign ownership in the building is within the 49 per cent limit, shown by the juristic person's records, before you pay."),
           ("Title and seller", "The title deed, registered owner, mortgages, seizures and the seller's authority to sell, including company sellers."),
           ("Funds and bank documents", "How the money must be remitted and documented so the Land Office accepts the unit as foreign-owned, and what goes wrong with late or wrong transfers."),
           ("Juristic person and fees", "Unpaid common-area fees and sinking fund, building rules, and any pending special charges that pass to the new owner."),
           ("Reservation and sale agreement", "Deposit protection, conditions for a refund, who bears which costs, and the points worth changing."),
           ("Transfer and taxes", "Registration at the Land Office, who pays which taxes and fees, and a correctly prepared power of attorney if you cannot attend.")],
    noEyebrow="If the quota is full",
    noTitle="Other routes exist, with trade-offs",
    noText="If the foreign quota in a building is already used, the unit cannot be registered in your name freehold. A long-term registered lease or another structure may be possible, with different rights and risks, and we explain them before you decide. We do not suggest arrangements that conceal foreign ownership.",
    fallbackTitle="Points we raise before you pay a deposit",
    fallbacks=["Written confirmation of the quota position from the juristic person",
               "A condition that the deposit is refunded if the unit cannot be transferred to you",
               "Evidence of the seller's ownership and a plan to discharge any mortgage at transfer",
               "Clarity on who pays transfer fees and taxes",
               "A plan for signing, remittance and transfer if you are abroad"],
    stages=[("Quota and title check:", "Verification of the foreign quota, ownership and encumbrances."),
            ("Contract review:", "A written review, with proposed changes, of the reservation and sale agreement."),
            ("Funds and documents:", "Guidance on remittance, the bank's foreign exchange documents and a power of attorney."),
            ("Transfer attendance:", "Support at the Land Office until the title is registered."),
            ("After purchase:", "A short note on ownership, renting out the unit, wills and ongoing building costs.")],
    faq=[("Can a foreigner own a condominium outright in Thailand?", "Yes, freehold, in your own name, within the foreign quota of 49 per cent of the total area of the building and with the purchase money brought in from abroad."),
         ("How do I know the quota is not full?", "The condominium juristic person and the Land Office records show the foreign share. We ask for written confirmation before you pay a deposit."),
         ("Can I buy through my Thai partner or a company?", "Holding a unit in a Thai partner's name or through a company has legal consequences, including who legally owns it, and some arrangements are not lawful. We explain the options and the risks plainly before you decide."),
         ("Do I need to be in Thailand to complete the purchase?", "Not necessarily. Many buyers sign through a power of attorney and send funds from abroad, with our attendance at the Land Office, but the power of attorney must be prepared correctly."),
         ("Which documents do you need?", "The reservation or draft sale agreement, a copy of the title deed, the seller's details, the building's juristic person documents and your passport details. We confirm conflicts before you share them.")],
)

C['th'] = dict(
    title="การซื้อคอนโดในประเทศไทยสำหรับชาวต่างชาติ: โควตาต่างชาติและการโอน | สำนักงานกฎหมายวลัยลักษณ์",
    description="บริการกฎหมายสำหรับชาวต่างชาติที่ซื้อคอนโดในไทย: โควตาต่างชาติ 49% การโอนเงินเข้าประเทศ การตรวจสอบ การตรวจสัญญา และการโอนที่สำนักงานที่ดิน",
    eyebrow="การซื้อคอนโดมิเนียม",
    h1="การซื้อคอนโดมิเนียมในประเทศไทยสำหรับชาวต่างชาติ",
    lead="บริการกฎหมายเป็นภาษาอังกฤษสำหรับชาวต่างชาติที่ซื้อห้องชุดมือสองและโครงการใหม่ ตั้งแต่การเสนอซื้อครั้งแรกจนถึงการจดทะเบียนที่สำนักงานที่ดิน ไม่ว่าคุณอยู่ในประเทศไทยหรือต่างประเทศ",
    introEyebrow="ผู้ซื้อชาวต่างชาติ",
    introTitle="ถือกรรมสิทธิ์เต็มได้ แต่ต้องอยู่ภายในโควตาของชาวต่างชาติ",
    intro="ชาวต่างชาติถือกรรมสิทธิ์ห้องชุดแบบเต็มในนามของตนเองได้ แต่ต้องอยู่ภายในโควตาของชาวต่างชาติ กล่าวคือ พ.ร.บ.อาคารชุดจำกัดการถือครองของชาวต่างชาติไว้ไม่เกินร้อยละ 49 ของพื้นที่รวมของอาคารชุดที่จดทะเบียน และเงินค่าซื้อต้องนำเข้าจากต่างประเทศเป็นเงินตราต่างประเทศพร้อมเอกสารยืนยันจากธนาคาร อาคารที่โควตาเต็มแล้ว ผู้ขายที่ยังมีภาระจำนอง ค่าส่วนกลางที่ค้างชำระ หรือการวางเงินมัดจำเร็วเกินไป อาจทำให้การซื้อที่ดูง่ายกลายเป็นปัญหาได้ สำนักงานกฎหมายวลัยลักษณ์ตรวจสอบห้องชุด โควตา ผู้ขาย และเอกสารก่อนที่คุณจะผูกพัน ตรวจสัญญาจองและสัญญาซื้อขาย และไปร่วมการโอนแทนคุณเมื่อจำเป็น สำหรับโครงการที่ยังก่อสร้างไม่เสร็จ โปรดดูบริการตรวจสอบสัญญาซื้อก่อนสร้างเสร็จของเรา",
    situations=["คอนโดมือสองในพัทยา จอมเทียน ระยอง หรือที่อื่น ก่อนวางเงินมัดจำ",
                "สัญญาจองหรือเงินมัดจำที่ถูกเรียกเก็บก่อนที่คุณจะได้เห็นเอกสารกรรมสิทธิ์",
                "ผู้ซื้อด้วยเงินสดที่จะโอนเงินมาจากต่างประเทศ",
                "ผู้ซื้อที่จะลงนามจากระยะไกลผ่านหนังสือมอบอำนาจ",
                "ผู้ขายที่เป็นนิติบุคคล หรือห้องชุดที่ยังติดจำนอง",
                "ชาวต่างชาติที่มีคู่ครองชาวไทยและกำลังตัดสินใจว่าจะถือกรรมสิทธิ์อย่างไร"],
    reviewTitle="สิ่งที่เราตรวจสอบก่อนคุณซื้อ",
    reviewIntro="เราตรวจสอบห้องชุด อาคาร และเอกสารตามลำดับที่ปกป้องเงินของคุณ",
    cards=[("โควตาต่างชาติ", "สัดส่วนการถือครองของชาวต่างชาติในอาคารอยู่ภายในร้อยละ 49 หรือไม่ ตามที่ปรากฏในบันทึกของนิติบุคคลอาคารชุด ก่อนที่คุณจะชำระเงิน"),
           ("กรรมสิทธิ์และผู้ขาย", "หนังสือกรรมสิทธิ์ห้องชุด ผู้ถือกรรมสิทธิ์ที่จดทะเบียน ภาระจำนอง การอายัด และอำนาจของผู้ขาย รวมถึงผู้ขายที่เป็นบริษัท"),
           ("เงินและเอกสารธนาคาร", "วิธีโอนเงินเข้าและทำเอกสารเพื่อให้สำนักงานที่ดินรับรองว่าเป็นห้องชุดของชาวต่างชาติ และปัญหาที่เกิดจากการโอนเงินล่าช้าหรือไม่ถูกต้อง"),
           ("นิติบุคคลอาคารชุดและค่าใช้จ่าย", "ค่าส่วนกลางและกองทุนสำรองที่ค้างชำระ ข้อบังคับของอาคาร และค่าใช้จ่ายพิเศษที่รอเรียกเก็บซึ่งจะตกแก่เจ้าของใหม่"),
           ("สัญญาจองและสัญญาซื้อขาย", "การคุ้มครองเงินมัดจำ เงื่อนไขการคืนเงิน ผู้รับภาระค่าใช้จ่ายแต่ละรายการ และประเด็นที่ควรแก้ไข"),
           ("การโอนและภาษี", "การจดทะเบียนที่สำนักงานที่ดิน ผู้รับผิดชอบภาษีและค่าธรรมเนียมแต่ละรายการ และหนังสือมอบอำนาจที่จัดทำถูกต้องหากคุณไม่สามารถไปด้วยตนเอง")],
    noEyebrow="เมื่อโควตาเต็ม",
    noTitle="ยังมีทางเลือกอื่น แต่มีข้อแลกเปลี่ยน",
    noText="หากโควตาของชาวต่างชาติในอาคารเต็มแล้ว ห้องชุดนั้นไม่สามารถจดทะเบียนในนามของคุณแบบกรรมสิทธิ์เต็มได้ อาจมีทางเลือกเป็นสิทธิการเช่าระยะยาวที่จดทะเบียนหรือโครงสร้างอื่น ซึ่งมีสิทธิและความเสี่ยงแตกต่างกัน เราอธิบายก่อนที่คุณจะตัดสินใจ และไม่เสนอการจัดการที่ปกปิดการถือครองของชาวต่างชาติ",
    fallbackTitle="ประเด็นที่เราหยิบยกก่อนคุณวางเงินมัดจำ",
    fallbacks=["หนังสือยืนยันสถานะโควตาจากนิติบุคคลอาคารชุด",
               "เงื่อนไขให้คืนเงินมัดจำหากไม่สามารถโอนห้องชุดให้คุณได้",
               "หลักฐานความเป็นเจ้าของของผู้ขาย และแผนไถ่ถอนจำนองในวันโอน",
               "ความชัดเจนว่าใครรับผิดชอบค่าธรรมเนียมและภาษีการโอน",
               "แผนการลงนาม การโอนเงิน และการโอนกรรมสิทธิ์ หากคุณอยู่ต่างประเทศ"],
    stages=[("ตรวจโควตาและกรรมสิทธิ์:", "ตรวจสอบโควตาต่างชาติ ความเป็นเจ้าของ และภาระผูกพัน"),
            ("ตรวจสัญญา:", "รายงานเป็นลายลักษณ์อักษรพร้อมข้อเสนอแก้ไขสัญญาจองและสัญญาซื้อขาย"),
            ("เงินและเอกสาร:", "แนวทางการโอนเงินเข้า เอกสารธุรกรรมเงินตราต่างประเทศของธนาคาร และหนังสือมอบอำนาจ"),
            ("ร่วมการโอน:", "สนับสนุนที่สำนักงานที่ดินจนกว่าจะจดทะเบียนกรรมสิทธิ์เสร็จ"),
            ("หลังการซื้อ:", "บันทึกสั้น ๆ เรื่องความเป็นเจ้าของ การให้เช่าห้องชุด พินัยกรรม และค่าใช้จ่ายของอาคารที่ต่อเนื่อง")],
    faq=[("ชาวต่างชาติถือกรรมสิทธิ์คอนโดแบบเต็มในประเทศไทยได้หรือไม่?", "ได้ ในนามของตนเอง ภายในโควตาต่างชาติร้อยละ 49 ของพื้นที่รวมของอาคาร และต้องนำเงินค่าซื้อเข้าจากต่างประเทศ"),
         ("จะทราบได้อย่างไรว่าโควตายังไม่เต็ม?", "นิติบุคคลอาคารชุดและบันทึกของสำนักงานที่ดินแสดงสัดส่วนของชาวต่างชาติ เราขอหนังสือยืนยันเป็นลายลักษณ์อักษรก่อนที่คุณจะวางเงินมัดจำ"),
         ("ซื้อผ่านคู่ครองชาวไทยหรือบริษัทได้หรือไม่?", "การถือห้องชุดในนามคู่ครองชาวไทยหรือผ่านบริษัทมีผลทางกฎหมาย รวมถึงว่าใครเป็นเจ้าของตามกฎหมาย และบางรูปแบบไม่ชอบด้วยกฎหมาย เราอธิบายทางเลือกและความเสี่ยงอย่างตรงไปตรงมาก่อนที่คุณจะตัดสินใจ"),
         ("ต้องอยู่ในประเทศไทยเพื่อทำการซื้อให้เสร็จหรือไม่?", "ไม่จำเป็น ผู้ซื้อหลายรายลงนามผ่านหนังสือมอบอำนาจและโอนเงินจากต่างประเทศ โดยเราไปร่วมที่สำนักงานที่ดิน แต่หนังสือมอบอำนาจต้องจัดทำอย่างถูกต้อง"),
         ("ต้องใช้เอกสารอะไรบ้าง?", "สัญญาจองหรือร่างสัญญาซื้อขาย สำเนาโฉนดห้องชุด ข้อมูลผู้ขาย เอกสารของนิติบุคคลอาคารชุด และข้อมูลหนังสือเดินทางของคุณ เราตรวจสอบความขัดแย้งทางผลประโยชน์ก่อนที่คุณจะส่งเอกสาร")],
)

C['fr'] = dict(
    title="Acheter un Condominium en Thaïlande en tant qu'Étranger : Quota et Transfert | Walailak Law Firm",
    description="Accompagnement juridique pour l'achat d'un condominium en Thaïlande par un étranger : quota de 49 %, fonds, vérifications, contrat et transfert au Land Office.",
    eyebrow="ACHAT DE CONDOMINIUM",
    h1="Acheter un Condominium en Thaïlande en tant qu'Étranger",
    lead="Un accompagnement juridique en anglais pour les acheteurs étrangers de lots de condominium neufs ou de seconde main, de la première offre à l'enregistrement au Land Office, que vous soyez en Thaïlande ou à l'étranger.",
    introEyebrow="Acheteurs étrangers",
    introTitle="La pleine propriété est possible, mais seulement dans le quota étranger",
    intro="Un étranger peut être propriétaire en pleine propriété d'un lot de condominium en son nom propre, mais seulement dans le quota étranger : la loi sur les condominiums limite la propriété étrangère à 49 % de la surface totale d'un immeuble enregistré, et le prix doit être apporté de l'étranger en devises et justifié par la banque. Un immeuble dont le quota est déjà utilisé, un vendeur dont le bien est hypothéqué, des charges de copropriété impayées ou un acompte versé trop tôt peuvent transformer un achat simple en problème. Walailak Law Firm vérifie le lot, le quota, le vendeur et les documents avant que vous vous engagiez, examine le contrat de réservation et de vente, et assiste au transfert pour vous si nécessaire. Pour les projets encore en construction, consultez notre revue de contrat d'achat sur plan.",
    situations=["Un condominium de seconde main à Pattaya, Jomtien, Rayong ou ailleurs, avant de verser un acompte",
                "Un contrat de réservation ou un acompte demandé avant que vous ayez vu le titre",
                "Un acheteur au comptant qui transférera des fonds depuis l'étranger",
                "Un acheteur qui signera à distance par procuration",
                "Un vendeur qui est une société, ou un lot encore hypothéqué",
                "Un acheteur étranger avec un partenaire thaïlandais qui se demande comment détenir le titre"],
    reviewTitle="Ce que nous vérifions avant l'achat",
    reviewIntro="Nous examinons le lot, l'immeuble et les documents dans l'ordre qui protège votre argent.",
    cards=[("Quota étranger", "La propriété étrangère de l'immeuble est-elle dans la limite de 49 %, d'après les registres de la personne morale, avant que vous payiez ?"),
           ("Titre et vendeur", "Le titre de propriété, le propriétaire enregistré, les hypothèques, les saisies et le pouvoir du vendeur, y compris pour un vendeur société."),
           ("Fonds et documents bancaires", "Comment les fonds doivent être transférés et documentés pour que le Land Office reconnaisse le lot comme détenu par un étranger, et ce qui se passe en cas de virement tardif ou erroné."),
           ("Personne morale et charges", "Les charges de copropriété et le fonds de réserve impayés, le règlement de l'immeuble et les appels de fonds en attente qui passent au nouveau propriétaire."),
           ("Réservation et contrat de vente", "La protection de l'acompte, les conditions de remboursement, qui supporte quels frais, et les points à faire modifier."),
           ("Transfert et taxes", "L'enregistrement au Land Office, qui paie quelles taxes et quels frais, et une procuration correctement rédigée si vous ne pouvez pas être présent.")],
    noEyebrow="Si le quota est atteint",
    noTitle="D'autres voies existent, avec des compromis",
    noText="Si le quota étranger de l'immeuble est déjà utilisé, le lot ne peut pas être enregistré à votre nom en pleine propriété. Un bail de longue durée enregistré ou une autre structure peut être possible, avec des droits et des risques différents, que nous vous expliquons avant que vous décidiez. Nous ne proposons pas de montages qui dissimulent la propriété étrangère.",
    fallbackTitle="Points que nous soulevons avant tout acompte",
    fallbacks=["Une confirmation écrite de la situation du quota par la personne morale",
               "Une condition prévoyant le remboursement de l'acompte si le lot ne peut pas vous être transféré",
               "La preuve de la propriété du vendeur et un plan de mainlevée de l'hypothèque lors du transfert",
               "Une clarification sur qui paie les frais et taxes de transfert",
               "Un plan pour la signature, le virement et le transfert si vous êtes à l'étranger"],
    stages=[("Contrôle du quota et du titre :", "Vérification du quota étranger, de la propriété et des charges."),
            ("Revue du contrat :", "Un examen écrit, avec modifications proposées, du contrat de réservation et de vente."),
            ("Fonds et documents :", "Conseils sur le transfert de fonds, les documents de change de la banque et la procuration."),
            ("Présence au transfert :", "Un appui au Land Office jusqu'à l'enregistrement du titre."),
            ("Après l'achat :", "Une courte note sur la propriété, la location du lot, le testament et les charges de l'immeuble.")],
    faq=[("Un étranger peut-il être pleinement propriétaire d'un condominium en Thaïlande ?", "Oui, en pleine propriété et en son nom propre, dans le quota étranger de 49 % de la surface totale de l'immeuble et avec un prix apporté de l'étranger."),
         ("Comment savoir si le quota n'est pas atteint ?", "La personne morale du condominium et les registres du Land Office indiquent la part étrangère. Nous demandons une confirmation écrite avant que vous versiez un acompte."),
         ("Puis-je acheter par l'intermédiaire de mon partenaire thaïlandais ou d'une société ?", "Détenir un lot au nom d'un partenaire thaïlandais ou par une société a des conséquences juridiques, notamment sur qui en est légalement propriétaire, et certains montages ne sont pas licites. Nous exposons clairement les options et les risques avant que vous décidiez."),
         ("Dois-je être en Thaïlande pour finaliser l'achat ?", "Pas forcément. De nombreux acheteurs signent par procuration et envoient les fonds depuis l'étranger, avec notre présence au Land Office, mais la procuration doit être correctement rédigée."),
         ("De quels documents avez-vous besoin ?", "Le contrat de réservation ou le projet de contrat de vente, une copie du titre, les coordonnées du vendeur, les documents de la personne morale de l'immeuble et les informations de votre passeport. Nous vérifions les conflits avant que vous les transmettiez.")],
)

C['zh'] = dict(
    title="外国人在泰国购买公寓：外资配额与过户 | 瓦莱拉克律师事务所",
    description="为在泰国购买公寓的外国人提供法律支持：49%外资配额、境外汇款、产权与卖方核查、合同审查及土地局过户，并以英文说明，适合身在泰国或海外的买家。",
    eyebrow="公寓购买",
    h1="外国人在泰国购买公寓",
    lead="为外国买家购买二手及新建公寓单位提供英文法律支持，从首次报价到在土地局登记，无论您身在泰国还是海外。",
    introEyebrow="外国买家",
    introTitle="可以持有完整产权，但必须在外资配额之内",
    intro="外国人可以以自己的名义完整持有公寓单位的产权，但必须在外资配额之内：《公寓法》将外国人持有的比例限制在已登记楼宇总面积的49%以内，并且购房款必须以外币从境外汇入，由银行出具证明文件。楼宇配额已用完、卖方房产仍有抵押、公共费用未缴，或过早支付定金，都可能让看似简单的交易变成麻烦。瓦莱拉克律师事务所会在您做出承诺之前核查单位、配额、卖方及相关文件，审查预订协议与买卖合同，并在需要时代您出席过户。对于仍在建设中的项目，请参阅我们的期房购房合同审查服务。",
    situations=["在芭堤雅、中天、罗勇或其他地方购买二手公寓，在支付定金之前",
                "在您看到产权文件之前就被要求签署预订协议或支付定金",
                "将从境外汇款的现金买家",
                "将通过授权委托书远程签署的买家",
                "卖方是公司，或单位仍有抵押",
                "有泰国伴侣的外国买家，正在考虑产权应如何持有"],
    reviewTitle="购买前我们核查的内容",
    reviewIntro="我们按照最能保护您资金的顺序，逐项核查单位、楼宇和文件。",
    cards=[("外资配额", "在您付款之前，根据公寓管理法人的记录，核实楼宇内外国人持有比例是否在49%以内。"),
           ("产权与卖方", "产权证、登记业主、抵押、查封，以及卖方的出售权限，包括公司卖方。"),
           ("资金与银行文件", "资金应如何汇入并留存证明，土地局才会承认该单位为外国人持有，以及汇款迟延或错误会带来的问题。"),
           ("管理法人与费用", "未缴的公共区域费用与公积金、楼宇规约，以及将转由新业主承担的待收特别费用。"),
           ("预订与买卖合同", "定金保护、退款条件、各项费用由谁承担，以及值得修改的条款。"),
           ("过户与税费", "在土地局办理登记，各项税费由谁承担，以及在您无法到场时正确准备的授权委托书。")],
    noEyebrow="配额已满时",
    noTitle="还有其他途径，但各有取舍",
    noText="如果楼宇的外资配额已经用完，该单位就无法以完整产权登记在您名下。也许可以采用已登记的长期租赁或其他结构，权利与风险各不相同，我们会在您决定之前加以说明。我们不会提出掩盖外资持有的安排。",
    fallbackTitle="支付定金之前我们会提出的事项",
    fallbacks=["由管理法人出具关于配额情况的书面确认",
               "约定如果单位无法过户给您，定金予以退还",
               "卖方所有权的证明，以及过户时解除抵押的安排",
               "明确由谁承担过户费用和税款",
               "如果您在海外，签署、汇款及过户的安排计划"],
    stages=[("配额与产权核查：", "核实外资配额、所有权及权利负担。"),
            ("合同审查：", "对预订协议和买卖合同出具书面审查意见及建议修改之处。"),
            ("资金与文件：", "就汇款、银行外汇文件及授权委托书提供指引。"),
            ("出席过户：", "在土地局提供协助，直至产权登记完成。"),
            ("购买之后：", "关于所有权、出租、遗嘱及楼宇后续费用的简短说明。")],
    faq=[("外国人可以在泰国完整持有公寓产权吗？", "可以，以自己的名义持有完整产权，须在楼宇总面积49%的外资配额之内，并且购房款从境外汇入。"),
         ("如何知道配额没有用完？", "公寓管理法人及土地局的记录会显示外国人持有的份额。我们会在您支付定金之前索取书面确认。"),
         ("可以通过泰国伴侣或公司购买吗？", "将单位登记在泰国伴侣名下或通过公司持有，会产生法律后果，包括谁在法律上拥有该单位，而且有些安排是不合法的。我们会在您决定之前清楚说明各种选择及其风险。"),
         ("完成购买需要人在泰国吗？", "不一定。许多买家通过授权委托书签署并从境外汇款，由我们到土地局出席，但授权委托书必须正确准备。"),
         ("需要提供哪些文件？", "预订协议或买卖合同草案、产权证复印件、卖方信息、楼宇管理法人的文件及您的护照信息。在您提供之前，我们会先做利益冲突核查。")],
)

PAGE = dict(
    slug='condominium-purchase-foreign-quota-thailand',
    heroimg='real-estate-lawyer.webp',
    practice='real-estate-lawyer',
    icons=['ti-building-community', 'ti-file-search', 'ti-currency-baht', 'ti-receipt', 'ti-file-text', 'ti-key'],
    related=['real-estate-lawyer', 'pattaya-property-due-diligence', 'rayong-property-due-diligence',
             'off-plan-property-purchase-review'],
    topic='property',
    C=C,
)
