"""Personal injury and road accident claims in Thailand for foreigners."""

C = {}

C['en'] = dict(
    title="Personal Injury & Road Accident Claims in Thailand for Foreigners | Walailak Law Firm",
    description="English-speaking help for foreign victims of road and other accidents in Thailand: compulsory insurance, compensation claims, police reports and time limits.",
    eyebrow="INJURY & ACCIDENT CLAIMS",
    h1="Personal Injury & Road Accident Claims in Thailand",
    lead="Independent English-language advice for foreigners injured in Thailand: the compulsory insurance, compensation from the person responsible, and the steps to take while you recover, in Thailand or abroad.",
    introEyebrow="Injured in Thailand",
    introTitle="Start with the evidence and the time limits",
    intro="After an accident in Thailand, several routes can run at the same time: a police report and any criminal case, a claim on the compulsory motor insurance, a claim against the responsible party or their insurer, and, where relevant, your own travel or health insurance. They follow different rules and deadlines, and what you sign or accept early can limit your later options. Walailak Law Firm reviews the police and medical documents, explains which routes are open to you and how realistic each one is, and acts for you in negotiations or in court if you choose to go ahead. We tell you honestly when the likely recovery does not justify the cost of a claim.",
    situations=["A motorbike, car or pedestrian accident, with a police report in Thai",
                "A settlement offer from an insurer that you are unsure about accepting",
                "An accident at work, at a hotel or on a construction site",
                "Injuries that are still developing, with treatment continuing",
                "A family member abroad who is dealing with the case remotely"],
    reviewTitle="What we look at",
    reviewIntro="We start from the documents and work out which claims are realistic.",
    cards=[("Police report and evidence", "The police record, findings on fault, medical reports, photographs, CCTV and witness details, and what is still missing."),
           ("Compulsory insurance", "Claims on the compulsory motor insurance, which can pay medical costs and fixed amounts regardless of fault, and how they interact with other claims."),
           ("Claim against the responsible party", "Compensation for medical costs, lost income, pain and suffering and long-term effects, and whether the other party's insurer is also liable."),
           ("Valuing the claim", "A realistic view of what can be claimed, which documents prove each item and how courts tend to treat it."),
           ("Time limits", "Claims for wrongful acts have strict limitation periods, often one year from learning of the damage and who is liable, and criminal time limits can differ."),
           ("Settlements and releases", "What to check before you sign a settlement or release, so you do not give up a larger claim by accident.")],
    noEyebrow="Realistic expectations",
    noTitle="Not every case justifies a claim",
    noText="Court claims take time, and the amounts recovered in Thailand are often lower than claimants expect, particularly where the responsible party has only compulsory insurance and few assets. We assess this early and tell you plainly whether to negotiate, claim or stop.",
    fallbackTitle="What we look at first",
    fallbacks=["Whether the other party or an employer has insurance or assets that can be reached",
               "Whether the compulsory insurance and your own insurance already cover part of the loss",
               "The medical outlook, so an early settlement does not undervalue a lasting injury",
               "Whether a negotiated settlement is likely to be faster than going to court",
               "What can be done remotely if you must return home"],
    stages=[("Case assessment:", "Review of the documents and a written view on the routes and realistic outcomes."),
            ("Insurance and police liaison:", "Support with the compulsory insurance claim and with communication with the investigating officer."),
            ("Demand and negotiation:", "A formal claim to the responsible party and their insurer, and settlement talks."),
            ("Court proceedings:", "Claims filed and run in the Thai courts if negotiation does not succeed."),
            ("Remote handling:", "Updates in English by email, video call or WhatsApp, with a power of attorney if you have left Thailand.")],
    faq=[("Can I claim if I was a tourist or only have a short stay?", "Yes. Foreigners can make claims in Thailand. If you have returned home, much of the work can be done remotely, and a power of attorney lets us act for you."),
         ("Do I need to pursue the police case to claim compensation?", "Not always. A civil claim for compensation and a criminal case are separate, although the police findings are often important evidence and some criminal outcomes affect timing."),
         ("What if the other driver only has compulsory insurance?", "Compulsory insurance gives limited, fixed cover. Whether more can be recovered depends on the other party's own assets, any voluntary insurance and the facts of the case, which we assess before you decide to claim."),
         ("How long do I have to bring a claim?", "Time limits are short. For civil claims for wrongful acts the period is generally one year from the day you knew of the damage and who is responsible, with an outer limit of ten years, and longer periods can apply where the act is also a crime. Do not wait to get advice."),
         ("Which documents do you need?", "The police report, medical reports and receipts, photographs, insurance details, any settlement offer and details of lost income. We confirm conflicts before you send documents.")],
)

C['th'] = dict(
    title="คดีบาดเจ็บและอุบัติเหตุทางถนนในประเทศไทยสำหรับชาวต่างชาติ | สำนักงานกฎหมายวลัยลักษณ์",
    description="ความช่วยเหลือเป็นภาษาอังกฤษสำหรับชาวต่างชาติที่ประสบอุบัติเหตุในไทย: ประกันภัย พ.ร.บ. การเรียกค่าสินไหมทดแทน รายงานตำรวจ และอายุความ",
    eyebrow="คดีบาดเจ็บและอุบัติเหตุ",
    h1="คดีบาดเจ็บและอุบัติเหตุทางถนนในประเทศไทย",
    lead="คำปรึกษาเป็นภาษาอังกฤษอย่างเป็นอิสระสำหรับชาวต่างชาติที่ได้รับบาดเจ็บในประเทศไทย ทั้งประกันภัยภาคบังคับ ค่าสินไหมทดแทนจากผู้รับผิดชอบ และขั้นตอนที่ควรทำระหว่างพักฟื้น ทั้งในประเทศไทยและต่างประเทศ",
    introEyebrow="บาดเจ็บในประเทศไทย",
    introTitle="เริ่มจากพยานหลักฐานและอายุความ",
    intro="หลังเกิดอุบัติเหตุในประเทศไทย อาจมีหลายช่องทางดำเนินไปพร้อมกัน ได้แก่ รายงานของตำรวจและคดีอาญา การเรียกเงินจากประกันภัยภาคบังคับ การเรียกร้องต่อผู้รับผิดชอบหรือบริษัทประกันของผู้นั้น และประกันการเดินทางหรือประกันสุขภาพของคุณเอง แต่ละช่องทางมีกฎและกำหนดเวลาแตกต่างกัน และสิ่งที่คุณลงนามหรือยอมรับในช่วงแรกอาจจำกัดทางเลือกในภายหลัง สำนักงานกฎหมายวลัยลักษณ์ตรวจสอบเอกสารจากตำรวจและโรงพยาบาล อธิบายว่าช่องทางใดเปิดให้คุณและมีความเป็นไปได้เพียงใด และดำเนินการแทนคุณในการเจรจาหรือในศาลหากคุณเลือกเดินหน้า เราจะบอกตามตรงเมื่อค่าเสียหายที่น่าจะได้รับไม่คุ้มกับค่าใช้จ่ายในการเรียกร้อง",
    situations=["อุบัติเหตุรถจักรยานยนต์ รถยนต์ หรือคนเดินเท้า พร้อมรายงานตำรวจเป็นภาษาไทย",
                "ข้อเสนอประนีประนอมจากบริษัทประกันที่คุณไม่แน่ใจว่าควรยอมรับหรือไม่",
                "อุบัติเหตุในที่ทำงาน ในโรงแรม หรือที่ไซต์ก่อสร้าง",
                "อาการบาดเจ็บที่ยังพัฒนาอยู่และยังรักษาต่อเนื่อง",
                "ญาติที่อยู่ต่างประเทศและดูแลเรื่องนี้จากระยะไกล"],
    reviewTitle="สิ่งที่เราพิจารณา",
    reviewIntro="เราเริ่มจากเอกสารและพิจารณาว่าข้อเรียกร้องใดเป็นไปได้จริง",
    cards=[("รายงานตำรวจและพยานหลักฐาน", "บันทึกของตำรวจ ข้อสรุปเรื่องฝ่ายผิด รายงานทางการแพทย์ ภาพถ่าย กล้องวงจรปิด รายชื่อพยาน และสิ่งที่ยังขาด"),
           ("ประกันภัยภาคบังคับ", "การเรียกร้องจากประกันภัยภาคบังคับของรถ ซึ่งอาจจ่ายค่ารักษาพยาบาลและเงินตามจำนวนที่กำหนดโดยไม่ต้องพิสูจน์ความผิด และความสัมพันธ์กับข้อเรียกร้องอื่น"),
           ("การเรียกร้องต่อผู้รับผิดชอบ", "ค่าสินไหมทดแทนสำหรับค่ารักษาพยาบาล รายได้ที่สูญเสีย ความเจ็บปวด และผลระยะยาว และบริษัทประกันของอีกฝ่ายต้องรับผิดด้วยหรือไม่"),
           ("การประเมินมูลค่าข้อเรียกร้อง", "มุมมองที่สมจริงว่าเรียกร้องอะไรได้บ้าง เอกสารใดพิสูจน์แต่ละรายการ และศาลมักพิจารณาอย่างไร"),
           ("อายุความ", "ข้อเรียกร้องจากการกระทำละเมิดมีอายุความที่เข้มงวด มักเป็นหนึ่งปีนับแต่ได้รู้ถึงความเสียหายและตัวผู้ต้องรับผิด และอายุความทางอาญาอาจแตกต่างกัน"),
           ("การประนีประนอมและหนังสือปลดเปลื้องความรับผิด", "สิ่งที่ต้องตรวจก่อนลงนามประนีประนอมหรือปลดเปลื้องความรับผิด เพื่อไม่ให้คุณสละข้อเรียกร้องที่ใหญ่กว่าโดยไม่ตั้งใจ")],
    noEyebrow="ความคาดหวังที่สมจริง",
    noTitle="ไม่ใช่ทุกคดีที่คุ้มกับการเรียกร้อง",
    noText="การฟ้องร้องใช้เวลา และจำนวนเงินที่ได้รับในประเทศไทยมักต่ำกว่าที่ผู้เรียกร้องคาดไว้ โดยเฉพาะเมื่อผู้รับผิดชอบมีเพียงประกันภัยภาคบังคับและมีทรัพย์สินน้อย เราประเมินเรื่องนี้ตั้งแต่ต้นและบอกตามตรงว่าควรเจรจา เรียกร้อง หรือยุติ",
    fallbackTitle="สิ่งที่เราพิจารณาก่อน",
    fallbacks=["อีกฝ่ายหรือนายจ้างมีประกันภัยหรือทรัพย์สินที่เข้าถึงได้หรือไม่",
               "ประกันภัยภาคบังคับและประกันของคุณเองครอบคลุมความเสียหายส่วนหนึ่งแล้วหรือไม่",
               "แนวโน้มทางการแพทย์ เพื่อไม่ให้การประนีประนอมเร็วเกินไปประเมินอาการบาดเจ็บถาวรต่ำเกินจริง",
               "การเจรจาประนีประนอมน่าจะเร็วกว่าการไปศาลหรือไม่",
               "สิ่งที่ทำจากระยะไกลได้หากคุณต้องเดินทางกลับบ้าน"],
    stages=[("ประเมินคดี:", "ตรวจเอกสารและให้ความเห็นเป็นลายลักษณ์อักษรเกี่ยวกับช่องทางและผลลัพธ์ที่สมจริง"),
            ("ประสานงานประกันและตำรวจ:", "สนับสนุนการเรียกร้องจากประกันภัยภาคบังคับและการติดต่อกับพนักงานสอบสวน"),
            ("ทวงถามและเจรจา:", "การเรียกร้องอย่างเป็นทางการต่อผู้รับผิดชอบและบริษัทประกัน และการเจรจาประนีประนอม"),
            ("การดำเนินคดีในศาล:", "ยื่นและดำเนินคดีในศาลไทยหากการเจรจาไม่สำเร็จ"),
            ("ดำเนินการจากระยะไกล:", "รายงานความคืบหน้าเป็นภาษาอังกฤษทางอีเมล วิดีโอคอล หรือ WhatsApp พร้อมหนังสือมอบอำนาจหากคุณออกจากประเทศไทยแล้ว")],
    faq=[("ฉันเป็นนักท่องเที่ยวหรือพำนักระยะสั้น ยังเรียกร้องได้หรือไม่?", "ได้ ชาวต่างชาติเรียกร้องในประเทศไทยได้ หากคุณกลับบ้านแล้ว งานส่วนใหญ่ทำจากระยะไกลได้ และหนังสือมอบอำนาจทำให้เราดำเนินการแทนคุณได้"),
         ("ต้องดำเนินคดีกับตำรวจก่อนจึงจะเรียกค่าสินไหมได้หรือไม่?", "ไม่เสมอไป การเรียกร้องทางแพ่งและคดีอาญาแยกจากกัน แม้ข้อสรุปของตำรวจมักเป็นพยานหลักฐานสำคัญ และผลของคดีอาญาบางอย่างมีผลต่อระยะเวลา"),
         ("ถ้าอีกฝ่ายมีเพียงประกันภัยภาคบังคับจะทำอย่างไร?", "ประกันภัยภาคบังคับให้ความคุ้มครองจำกัดตามจำนวนที่กำหนด จะเรียกเพิ่มได้หรือไม่ขึ้นกับทรัพย์สินของอีกฝ่าย ประกันภาคสมัครใจ และข้อเท็จจริงของคดี ซึ่งเราประเมินก่อนที่คุณจะตัดสินใจเรียกร้อง"),
         ("มีเวลานานเท่าใดในการเรียกร้อง?", "อายุความสั้น สำหรับข้อเรียกร้องทางแพ่งจากการละเมิด โดยทั่วไปคือหนึ่งปีนับแต่วันที่รู้ถึงความเสียหายและตัวผู้ต้องรับผิด และไม่เกินสิบปี ทั้งนี้อาจมีอายุความที่ยาวกว่าหากการกระทำนั้นเป็นความผิดอาญาด้วย อย่ารอที่จะขอคำปรึกษา"),
         ("ต้องใช้เอกสารอะไรบ้าง?", "รายงานตำรวจ รายงานและใบเสร็จทางการแพทย์ ภาพถ่าย รายละเอียดประกันภัย ข้อเสนอประนีประนอม (ถ้ามี) และรายละเอียดรายได้ที่สูญเสีย เราตรวจสอบความขัดแย้งทางผลประโยชน์ก่อนที่คุณจะส่งเอกสาร")],
)

C['fr'] = dict(
    title="Dommages Corporels et Accidents de la Route en Thaïlande pour les Étrangers | Walailak Law Firm",
    description="Aide en anglais pour les victimes étrangères d'accidents en Thaïlande : assurance obligatoire, demande d'indemnisation, rapport de police et délais.",
    eyebrow="DOMMAGES CORPORELS ET ACCIDENTS",
    h1="Dommages Corporels et Accidents de la Route en Thaïlande",
    lead="Des conseils indépendants, en anglais, pour les étrangers blessés en Thaïlande : l'assurance obligatoire, l'indemnisation par le responsable et les démarches à suivre pendant votre rétablissement, en Thaïlande ou à l'étranger.",
    introEyebrow="Blessé en Thaïlande",
    introTitle="Commencer par les preuves et les délais",
    intro="Après un accident en Thaïlande, plusieurs voies peuvent s'ouvrir en même temps : un rapport de police et une éventuelle procédure pénale, une demande auprès de l'assurance automobile obligatoire, une réclamation contre le responsable ou son assureur et, le cas échéant, votre propre assurance voyage ou santé. Elles obéissent à des règles et des délais différents, et ce que vous signez ou acceptez tôt peut limiter vos options ultérieures. Walailak Law Firm examine les documents de police et médicaux, explique quelles voies vous sont ouvertes et leur réalisme, et agit pour vous dans la négociation ou devant le tribunal si vous décidez de poursuivre. Nous vous disons honnêtement lorsque l'indemnisation probable ne justifie pas le coût d'une action.",
    situations=["Un accident de moto, de voiture ou de piéton, avec un rapport de police en thaï",
                "Une offre de règlement d'un assureur que vous hésitez à accepter",
                "Un accident du travail, à l'hôtel ou sur un chantier",
                "Des blessures qui évoluent encore, avec des soins qui se poursuivent",
                "Un proche à l'étranger qui suit le dossier à distance"],
    reviewTitle="Ce que nous examinons",
    reviewIntro="Nous partons des documents pour déterminer quelles demandes sont réalistes.",
    cards=[("Rapport de police et preuves", "Le procès-verbal, les conclusions sur les responsabilités, les rapports médicaux, les photos, la vidéosurveillance, les témoins, et ce qui manque encore."),
           ("Assurance obligatoire", "Les demandes auprès de l'assurance automobile obligatoire, qui peut couvrir des frais médicaux et des montants fixes quelle que soit la faute, et leur articulation avec les autres demandes."),
           ("Demande contre le responsable", "L'indemnisation des frais médicaux, de la perte de revenus, du préjudice moral et des séquelles à long terme, et la responsabilité éventuelle de l'assureur de l'autre partie."),
           ("Évaluation de la demande", "Une vision réaliste de ce qui peut être réclamé, des pièces qui prouvent chaque poste et de la façon dont les tribunaux le traitent."),
           ("Délais", "Les actions pour faute ont des délais de prescription stricts, souvent un an à compter de la connaissance du dommage et du responsable, et les délais pénaux peuvent différer."),
           ("Transactions et quittances", "Ce qu'il faut vérifier avant de signer une transaction ou une quittance, pour ne pas renoncer par erreur à une demande plus importante.")],
    noEyebrow="Attentes réalistes",
    noTitle="Toutes les affaires ne justifient pas une action",
    noText="Les procédures judiciaires prennent du temps, et les sommes obtenues en Thaïlande sont souvent inférieures à ce que les victimes espèrent, surtout lorsque le responsable n'a que l'assurance obligatoire et peu de biens. Nous l'évaluons tôt et vous disons franchement s'il faut négocier, agir ou s'arrêter.",
    fallbackTitle="Ce que nous examinons d'abord",
    fallbacks=["Si l'autre partie ou un employeur dispose d'une assurance ou de biens saisissables",
               "Si l'assurance obligatoire et votre propre assurance couvrent déjà une partie du préjudice",
               "Le pronostic médical, pour qu'un règlement précoce ne sous-évalue pas une blessure durable",
               "Si une transaction négociée sera probablement plus rapide qu'un procès",
               "Ce qui peut être fait à distance si vous devez rentrer chez vous"],
    stages=[("Évaluation du dossier :", "Examen des documents et avis écrit sur les voies possibles et les résultats réalistes."),
            ("Assurance et police :", "Appui pour la demande à l'assurance obligatoire et pour les échanges avec l'officier chargé de l'enquête."),
            ("Mise en demeure et négociation :", "Une réclamation formelle au responsable et à son assureur, puis les discussions de règlement."),
            ("Procédure judiciaire :", "Actions engagées et conduites devant les tribunaux thaïlandais si la négociation échoue."),
            ("Suivi à distance :", "Des comptes rendus en anglais par e-mail, visioconférence ou WhatsApp, avec une procuration si vous avez quitté la Thaïlande.")],
    faq=[("Puis-je agir si je suis touriste ou en séjour court ?", "Oui. Les étrangers peuvent agir en Thaïlande. Si vous êtes rentré chez vous, une grande partie du travail peut se faire à distance, et une procuration nous permet d'agir pour vous."),
         ("Dois-je poursuivre l'affaire pénale pour être indemnisé ?", "Pas toujours. L'action civile en indemnisation et l'affaire pénale sont distinctes, même si les conclusions de la police sont souvent une preuve importante et si certaines issues pénales influent sur le calendrier."),
         ("Et si l'autre conducteur n'a que l'assurance obligatoire ?", "L'assurance obligatoire offre une couverture limitée et forfaitaire. Savoir si l'on peut obtenir davantage dépend des biens de l'autre partie, d'une éventuelle assurance volontaire et des faits, ce que nous évaluons avant que vous décidiez d'agir."),
         ("De combien de temps dispose-je pour agir ?", "Les délais sont courts. Pour les actions civiles en responsabilité, le délai est en général d'un an à compter du jour où vous avez connu le dommage et le responsable, avec une limite absolue de dix ans, et des délais plus longs peuvent s'appliquer si l'acte est aussi une infraction. N'attendez pas pour demander conseil."),
         ("De quels documents avez-vous besoin ?", "Le rapport de police, les rapports et factures médicaux, les photos, les détails d'assurance, toute offre de règlement et les informations sur la perte de revenus. Nous vérifions les conflits avant que vous envoyiez des documents.")],
)

C['zh'] = dict(
    title="外国人在泰国的人身伤害与交通事故索赔 | 瓦莱拉克律师事务所",
    description="为在泰国遭遇交通及其他事故的外国受害人提供英文协助：强制保险、向责任方索赔、警方报告审查、和解风险及时效提醒，适合身在泰国或海外的受害人。",
    eyebrow="伤害与事故索赔",
    h1="泰国人身伤害与交通事故索赔",
    lead="为在泰国受伤的外国人提供独立的英文咨询：强制保险、向责任方索赔，以及您康复期间无论身在泰国还是海外应采取的步骤。",
    introEyebrow="在泰国受伤",
    introTitle="从证据和时效入手",
    intro="在泰国发生事故后，可能同时有几条途径并行：警方报告及可能的刑事案件、向强制机动车保险索赔、向责任方或其保险公司索赔，以及在适用时使用您自己的旅行或健康保险。它们适用不同的规则和期限，而且您早期签署或接受的内容可能限制日后的选择。瓦莱拉克律师事务所审阅警方和医疗文件，说明哪些途径对您开放以及各自的现实可行性，并在您决定推进时代您进行谈判或出庭。当预期的赔偿不足以抵偿索赔成本时，我们会如实告诉您。",
    situations=["摩托车、汽车或行人事故，附有泰文警方报告",
                "保险公司提出的和解方案，您不确定是否应当接受",
                "工作中、酒店内或建筑工地上的事故",
                "伤情仍在发展、治疗仍在继续",
                "身在海外、远程处理案件的家属"],
    reviewTitle="我们审查的内容",
    reviewIntro="我们从文件入手，判断哪些索赔是现实可行的。",
    cards=[("警方报告与证据", "警方记录、过错认定、医疗报告、照片、监控录像与证人信息，以及仍然缺少的材料。"),
           ("强制保险", "向强制机动车保险索赔，该保险无论有无过错均可支付医疗费用和固定金额，以及它与其他索赔之间的关系。"),
           ("向责任方索赔", "医疗费用、收入损失、精神痛苦和长期影响的赔偿，以及对方的保险公司是否也要承担责任。"),
           ("评估索赔价值", "对可以索赔内容的现实判断、各项所需的证明文件，以及法院通常如何处理。"),
           ("时效", "侵权类索赔有严格的时效，通常自知道损害及赔偿义务人之日起一年，刑事时效可能不同。"),
           ("和解与免责", "签署和解协议或免责声明之前应核查的事项，避免无意中放弃更大的索赔。")],
    noEyebrow="合理预期",
    noTitle="并非每个案件都值得索赔",
    noText="诉讼需要时间，在泰国实际获得的赔偿往往低于索赔人的预期，尤其是责任方只有强制保险且资产有限时。我们会尽早评估，并如实告诉您应当谈判、索赔还是止步。",
    fallbackTitle="我们首先查看的事项",
    fallbacks=["对方或雇主是否有可追偿的保险或资产",
               "强制保险和您自己的保险是否已经覆盖了部分损失",
               "医疗预后，避免过早和解低估了长期伤害",
               "协商和解是否可能比诉讼更快",
               "如果您必须回国，哪些事情可以远程办理"],
    stages=[("案件评估：", "审阅文件，并就可行途径和现实结果出具书面意见。"),
            ("保险与警方联络：", "协助办理强制保险索赔，并与办案警官沟通。"),
            ("索赔函与谈判：", "向责任方及其保险公司正式索赔，并进行和解谈判。"),
            ("诉讼：", "协商不成时，在泰国法院提起并办理索赔。"),
            ("远程办理：", "以英文通过电子邮件、视频通话或WhatsApp汇报进展；如果您已离开泰国，则凭授权委托书办理。")],
    faq=[("我是游客或只短期停留，还可以索赔吗？", "可以。外国人可以在泰国提出索赔。如果您已回国，大部分工作可以远程完成，授权委托书让我们能够代表您行事。"),
         ("要获得赔偿，必须追究警方的刑事案件吗？", "不一定。民事赔偿索赔与刑事案件是分开的，不过警方的认定通常是重要证据，某些刑事结果也会影响时间安排。"),
         ("如果对方司机只有强制保险怎么办？", "强制保险的保障有限且金额固定。能否追偿更多，取决于对方自身的资产、是否有自愿保险以及案件事实，我们会在您决定索赔之前加以评估。"),
         ("我有多长时间提出索赔？", "时效很短。就侵权的民事索赔而言，期限一般自您知道损害及责任人之日起一年，最长不超过十年；如果该行为同时构成犯罪，可能适用更长的期限。请不要拖延咨询。"),
         ("需要提供哪些文件？", "警方报告、医疗报告和收据、照片、保险信息、任何和解方案及收入损失的详情。在您提供文件之前，我们会先做利益冲突核查。")],
)

PAGE = dict(
    slug='personal-injury-accident-claims-thailand',
    heroimg='civil-litigation-lawyer.webp',
    practice='civil-litigation-services',
    icons=['ti-ambulance', 'ti-shield-check', 'ti-scale', 'ti-report-money', 'ti-clock', 'ti-file-text'],
    related=['civil-litigation-services', 'criminal-defence-lawyer', 'pattaya-criminal-defence-appeals'],
    topic='disputes',
    C=C,
)
