"""Setting up and licensing a bar, restaurant or entertainment venue in Pattaya."""

C = {}

C['en'] = dict(
    title="Bar & Entertainment Venue Setup and Licensing in Pattaya | Walailak Law Firm",
    description="Legal setup for bars, restaurants and entertainment venues in Pattaya: lawful structure, foreign ownership, alcohol and venue licences, staff and work permits.",
    eyebrow="HOSPITALITY & ENTERTAINMENT",
    h1="Bar & Entertainment Venue Setup and Licensing in Pattaya",
    lead="Company structure, licences, premises checks and staffing rules for foreign investors opening or buying a bar, restaurant or entertainment venue in Pattaya and Chonburi.",
    introEyebrow="Venue owners and investors",
    introTitle="Get the structure and the licences right before you open",
    intro="A bar or entertainment venue sits at the crossing of several sets of rules: limits on foreign ownership, local licensing for alcohol and entertainment, zoning and building use, employment and work-permit requirements, and tax. Enforcement against nominee structures has increased, and a venue set up the wrong way can lose its licences or be closed. Walailak Law Firm helps you choose a lawful structure, checks the premises before you sign a lease, guides the licences and permits, and sets up the staffing and contract framework, so the business can operate sustainably. We advise on legal and regulatory compliance. We do not recommend arrangements that disguise foreign ownership.",
    situations=["A foreign investor planning a bar, restaurant or live-music venue in Pattaya or Jomtien",
                "A buyer of an existing bar who needs the company, lease, licences and debts checked first",
                "A business that wants to add music, DJ events or longer opening hours",
                "An owner unsure how to engage managers, bartenders and entertainment staff lawfully",
                "An existing venue facing an inspection, a licence renewal or a labour complaint"],
    reviewTitle="What we help with",
    reviewIntro="We cover the main legal areas a venue has to get right.",
    cards=[("Ownership and structure", "Foreign majority ownership of service businesses is restricted. We explain the lawful options, such as a Foreign Business Licence or another approval, and why nominee shareholders are a legal and enforcement risk."),
           ("Premises and zoning", "Whether the building and location can lawfully be used as a bar or entertainment venue, and the lease terms that matter."),
           ("Licences", "Alcohol sales licences, entertainment venue licences, business registrations and, where relevant, music and performance permissions."),
           ("Staff and work permits", "Work permits for foreign managers, the Thai staffing requirement that usually applies and how to meet it, and employment contracts."),
           ("Contractors, commission and social security", "Whether staff are employees or genuine independent contractors, commission arrangements, tax and social security."),
           ("Inspections and compliance", "Preparing for inspections, renewals and complaints, and dealing with the authorities in Pattaya and Chonburi.")],
    noEyebrow="Before you commit",
    noTitle="Check the premises and the structure before the lease",
    noText="The most expensive mistakes happen before opening: signing a long lease on premises that cannot be licensed, buying a bar with hidden debts or labour claims, or using a structure that will not survive an inspection. We look at these early so you can renegotiate or walk away.",
    fallbackTitle="What we check before you sign",
    fallbacks=["The lease term, break clauses and who is responsible for licences",
               "The zoning and building-use status of the premises",
               "The company, debts, tax and staff records of a bar you are buying",
               "Whether your concept is lawful with the licences that are available",
               "A realistic timeline and budget for licences and staffing"],
    stages=[("Structure and feasibility advice:", "A written recommendation on ownership, capital and approvals."),
            ("Premises and lease review:", "Checks and negotiation points before you commit to a lease."),
            ("Company and licences:", "Company registration, business registration and licence applications."),
            ("Staff and work permits:", "Employment contracts, work permit applications and compliance procedures."),
            ("Ongoing support:", "Renewals, inspections and labour matters after opening.")],
    faq=[("Can a foreigner own 100% of a bar in Thailand?", "Service businesses such as bars are generally restricted for majority foreign ownership under the Foreign Business Act unless a licence or other approval applies. We explain what is realistic for your concept and which structures are lawful."),
         ("Is a Thai nominee shareholder an option?", "No. Using nominees to hold shares on behalf of a foreigner is unlawful and is a focus of current enforcement. We do not recommend or set up such arrangements."),
         ("Can you help me buy an existing bar?", "Yes. We check the company, lease, licences, debts, staff records and tax position before you pay, and advise on how to structure the purchase."),
         ("How should entertainment staff be engaged?", "It depends on the real working relationship. Some people are employees, and treating them as freelancers to avoid obligations creates risk. We look at the actual arrangement and advise on the lawful options."),
         ("Can you act for me with the authorities in Pattaya?", "We assist with applications, inspections and renewals in Pattaya and Chonburi, and tell you what each authority needs.")],
)

C['th'] = dict(
    title="การจัดตั้งและขอใบอนุญาตบาร์และสถานบันเทิงในพัทยา | สำนักงานกฎหมายวลัยลักษณ์",
    description="บริการกฎหมายสำหรับบาร์ ร้านอาหาร และสถานบันเทิงในพัทยา: โครงสร้างบริษัทที่ถูกต้อง การถือหุ้นของชาวต่างชาติ ใบอนุญาตสุราและสถานบริการ พนักงาน และใบอนุญาตทำงาน",
    eyebrow="ธุรกิจโรงแรมและสถานบันเทิง",
    h1="การจัดตั้งและขอใบอนุญาตบาร์และสถานบันเทิงในพัทยา",
    lead="โครงสร้างบริษัท ใบอนุญาต การตรวจสอบสถานที่ และกฎเรื่องพนักงาน สำหรับนักลงทุนต่างชาติที่เปิดหรือซื้อบาร์ ร้านอาหาร หรือสถานบันเทิงในพัทยาและชลบุรี",
    introEyebrow="เจ้าของสถานที่และนักลงทุน",
    introTitle="จัดโครงสร้างและใบอนุญาตให้ถูกต้องก่อนเปิดกิจการ",
    intro="บาร์หรือสถานบันเทิงเกี่ยวข้องกับกฎหลายชุด ได้แก่ ข้อจำกัดการถือหุ้นของชาวต่างชาติ ใบอนุญาตท้องถิ่นสำหรับสุราและความบันเทิง การใช้ที่ดินและอาคาร ข้อกำหนดด้านการจ้างงานและใบอนุญาตทำงาน และภาษี การบังคับใช้กฎหมายต่อโครงสร้างที่ใช้ตัวแทนถือหุ้นแทน (นอมินี) เพิ่มมากขึ้น และสถานที่ที่จัดตั้งผิดวิธีอาจถูกเพิกถอนใบอนุญาตหรือถูกสั่งปิด สำนักงานกฎหมายวลัยลักษณ์ช่วยคุณเลือกโครงสร้างที่ถูกต้องตามกฎหมาย ตรวจสอบสถานที่ก่อนคุณลงนามสัญญาเช่า แนะนำการขอใบอนุญาต และวางกรอบเรื่องพนักงานและสัญญา เพื่อให้ธุรกิจดำเนินงานได้อย่างยั่งยืน เราให้คำปรึกษาด้านการปฏิบัติตามกฎหมายและกฎระเบียบ และไม่แนะนำการจัดการที่ปกปิดการถือครองของชาวต่างชาติ",
    situations=["นักลงทุนต่างชาติที่วางแผนเปิดบาร์ ร้านอาหาร หรือสถานที่ดนตรีสดในพัทยาหรือจอมเทียน",
                "ผู้ซื้อบาร์ที่เปิดดำเนินการอยู่ซึ่งต้องตรวจสอบบริษัท สัญญาเช่า ใบอนุญาต และหนี้สินก่อน",
                "ธุรกิจที่ต้องการเพิ่มดนตรี กิจกรรมดีเจ หรือขยายเวลาเปิด",
                "เจ้าของที่ไม่แน่ใจว่าจะว่าจ้างผู้จัดการ บาร์เทนเดอร์ และพนักงานบันเทิงอย่างถูกต้องได้อย่างไร",
                "สถานที่ที่กำลังเผชิญการตรวจสอบ การต่อใบอนุญาต หรือข้อร้องเรียนด้านแรงงาน"],
    reviewTitle="สิ่งที่เราช่วยได้",
    reviewIntro="เราครอบคลุมด้านกฎหมายหลักที่สถานที่ต้องทำให้ถูกต้อง",
    cards=[("การถือหุ้นและโครงสร้าง", "การถือหุ้นข้างมากของชาวต่างชาติในธุรกิจบริการถูกจำกัด เราอธิบายทางเลือกที่ถูกกฎหมาย เช่น ใบอนุญาตประกอบธุรกิจของคนต่างด้าวหรือการอนุญาตอื่น และเหตุที่ผู้ถือหุ้นนอมินีเป็นความเสี่ยงทางกฎหมายและการบังคับใช้"),
           ("สถานที่และการใช้ที่ดิน", "อาคารและทำเลนั้นใช้เป็นบาร์หรือสถานบันเทิงได้โดยชอบด้วยกฎหมายหรือไม่ และเงื่อนไขในสัญญาเช่าที่สำคัญ"),
           ("ใบอนุญาต", "ใบอนุญาตขายสุรา ใบอนุญาตสถานบริการ การจดทะเบียนธุรกิจ และการอนุญาตเรื่องดนตรีและการแสดงในกรณีที่เกี่ยวข้อง"),
           ("พนักงานและใบอนุญาตทำงาน", "ใบอนุญาตทำงานสำหรับผู้จัดการต่างชาติ ข้อกำหนดเรื่องการจ้างพนักงานไทยที่มักใช้บังคับและวิธีปฏิบัติให้ครบ และสัญญาจ้าง"),
           ("ผู้รับจ้างอิสระ ค่าคอมมิชชัน และประกันสังคม", "พนักงานเป็นลูกจ้างหรือผู้รับจ้างอิสระจริงหรือไม่ การจัดการค่าคอมมิชชัน ภาษี และประกันสังคม"),
           ("การตรวจสอบและการปฏิบัติตามกฎหมาย", "เตรียมรับมือการตรวจสอบ การต่ออายุ และข้อร้องเรียน และการติดต่อหน่วยงานในพัทยาและชลบุรี")],
    noEyebrow="ก่อนผูกพัน",
    noTitle="ตรวจสอบสถานที่และโครงสร้างก่อนทำสัญญาเช่า",
    noText="ความผิดพลาดที่แพงที่สุดเกิดขึ้นก่อนเปิดกิจการ ได้แก่ การลงนามสัญญาเช่าระยะยาวในสถานที่ที่ขอใบอนุญาตไม่ได้ การซื้อบาร์ที่มีหนี้หรือข้อเรียกร้องด้านแรงงานแอบแฝง หรือการใช้โครงสร้างที่ไม่ผ่านการตรวจสอบ เราตรวจสอบเรื่องเหล่านี้ตั้งแต่เนิ่น ๆ เพื่อให้คุณเจรจาใหม่หรือถอนตัวได้",
    fallbackTitle="สิ่งที่เราตรวจสอบก่อนคุณลงนาม",
    fallbacks=["ระยะเวลาเช่า เงื่อนไขการเลิกสัญญา และผู้รับผิดชอบเรื่องใบอนุญาต",
               "สถานะการใช้ที่ดินและอาคารของสถานที่",
               "บริษัท หนี้สิน ภาษี และบันทึกพนักงานของบาร์ที่คุณจะซื้อ",
               "แนวคิดธุรกิจของคุณชอบด้วยกฎหมายกับใบอนุญาตที่มีอยู่หรือไม่",
               "กรอบเวลาและงบประมาณที่สมจริงสำหรับใบอนุญาตและพนักงาน"],
    stages=[("คำปรึกษาโครงสร้างและความเป็นไปได้:", "ข้อเสนอแนะเป็นลายลักษณ์อักษรเรื่องการถือหุ้น ทุน และการอนุญาต"),
            ("ตรวจสถานที่และสัญญาเช่า:", "การตรวจสอบและประเด็นเจรจาก่อนคุณผูกพันตามสัญญาเช่า"),
            ("บริษัทและใบอนุญาต:", "จดทะเบียนบริษัท จดทะเบียนธุรกิจ และยื่นขอใบอนุญาต"),
            ("พนักงานและใบอนุญาตทำงาน:", "สัญญาจ้าง การขอใบอนุญาตทำงาน และขั้นตอนการปฏิบัติตามกฎหมาย"),
            ("การสนับสนุนต่อเนื่อง:", "การต่ออายุ การตรวจสอบ และเรื่องแรงงานหลังเปิดกิจการ")],
    faq=[("ชาวต่างชาติถือหุ้นบาร์ในประเทศไทยได้ร้อยละ 100 หรือไม่?", "ธุรกิจบริการอย่างบาร์ถูกจำกัดการถือหุ้นข้างมากของชาวต่างชาติตามกฎหมายการประกอบธุรกิจของคนต่างด้าว เว้นแต่จะมีใบอนุญาตหรือการอนุญาตอื่น เราอธิบายว่าอะไรเป็นไปได้จริงสำหรับแนวคิดของคุณและโครงสร้างใดถูกกฎหมาย"),
         ("ใช้ผู้ถือหุ้นนอมินีชาวไทยได้หรือไม่?", "ไม่ได้ การใช้นอมินีถือหุ้นแทนชาวต่างชาติผิดกฎหมายและเป็นจุดเน้นของการบังคับใช้ในปัจจุบัน เราไม่แนะนำหรือจัดทำการจัดการเช่นนั้น"),
         ("ช่วยซื้อบาร์ที่เปิดอยู่ได้หรือไม่?", "ได้ เราตรวจสอบบริษัท สัญญาเช่า ใบอนุญาต หนี้สิน บันทึกพนักงาน และฐานะภาษีก่อนคุณชำระเงิน และแนะนำวิธีจัดโครงสร้างการซื้อ"),
         ("ควรว่าจ้างพนักงานบันเทิงอย่างไร?", "ขึ้นกับลักษณะความสัมพันธ์ในการทำงานที่แท้จริง บางคนเป็นลูกจ้าง และการปฏิบัติต่อพวกเขาเป็นผู้รับจ้างอิสระเพื่อเลี่ยงภาระมีความเสี่ยง เราพิจารณาข้อตกลงที่เป็นจริงและแนะนำทางเลือกที่ชอบด้วยกฎหมาย"),
         ("ดำเนินการกับหน่วยงานในพัทยาแทนฉันได้หรือไม่?", "เราช่วยเรื่องการยื่นคำขอ การตรวจสอบ และการต่ออายุในพัทยาและชลบุรี และแจ้งว่าแต่ละหน่วยงานต้องการอะไร")],
)

C['fr'] = dict(
    title="Création et Licences de Bar et Établissement de Divertissement à Pattaya | Walailak Law Firm",
    description="Montage juridique d'un bar, restaurant ou lieu de divertissement à Pattaya : structure licite, propriété étrangère, licences, personnel et permis de travail.",
    eyebrow="HÔTELLERIE ET DIVERTISSEMENT",
    h1="Création et Licences de Bar et Établissement de Divertissement à Pattaya",
    lead="Structure de société, licences, vérification des locaux et règles sur le personnel pour les investisseurs étrangers qui ouvrent ou rachètent un bar, un restaurant ou un lieu de divertissement à Pattaya et dans la province de Chonburi.",
    introEyebrow="Exploitants et investisseurs",
    introTitle="Bien régler la structure et les licences avant l'ouverture",
    intro="Un bar ou un établissement de divertissement se situe au croisement de plusieurs séries de règles : limites à la propriété étrangère, licences locales pour l'alcool et le divertissement, urbanisme et usage des bâtiments, emploi et permis de travail, et fiscalité. Les contrôles contre les montages avec prête-noms se sont renforcés, et un établissement mal structuré peut perdre ses licences ou être fermé. Walailak Law Firm vous aide à choisir une structure licite, vérifie les locaux avant la signature du bail, vous guide pour les licences et autorisations, et met en place le cadre du personnel et des contrats, afin que l'activité puisse durer. Nous conseillons sur la conformité légale et réglementaire. Nous ne recommandons pas de montages qui dissimulent la propriété étrangère.",
    situations=["Un investisseur étranger qui prévoit un bar, un restaurant ou une salle de musique live à Pattaya ou Jomtien",
                "Un repreneur d'un bar existant qui doit faire vérifier la société, le bail, les licences et les dettes",
                "Une entreprise qui veut ajouter de la musique, des soirées DJ ou des horaires plus longs",
                "Un exploitant qui ne sait pas comment engager légalement des gérants, des barmans et du personnel d'animation",
                "Un établissement confronté à un contrôle, à un renouvellement de licence ou à une plainte en droit du travail"],
    reviewTitle="Ce que nous faisons pour vous",
    reviewIntro="Nous couvrons les principaux domaines juridiques qu'un établissement doit maîtriser.",
    cards=[("Propriété et structure", "La détention majoritaire étrangère des activités de service est limitée. Nous expliquons les options licites, comme la licence d'activité pour étrangers ou une autre autorisation, et pourquoi les prête-noms sont un risque juridique et de contrôle."),
           ("Locaux et zonage", "Les locaux et leur emplacement peuvent-ils légalement servir de bar ou de lieu de divertissement, et quelles clauses du bail comptent."),
           ("Licences", "Licences de vente d'alcool, licences d'établissement de divertissement, immatriculations et, le cas échéant, autorisations de musique et de spectacle."),
           ("Personnel et permis de travail", "Permis de travail pour les gérants étrangers, l'exigence de personnel thaïlandais qui s'applique généralement et la façon d'y répondre, et les contrats de travail."),
           ("Prestataires, commissions et sécurité sociale", "Le personnel est-il salarié ou réellement indépendant, les systèmes de commission, la fiscalité et la sécurité sociale."),
           ("Contrôles et conformité", "La préparation aux contrôles, aux renouvellements et aux plaintes, et les relations avec les autorités à Pattaya et à Chonburi.")],
    noEyebrow="Avant de vous engager",
    noTitle="Vérifier les locaux et la structure avant le bail",
    noText="Les erreurs les plus coûteuses surviennent avant l'ouverture : signer un long bail pour des locaux qui ne peuvent pas être autorisés, racheter un bar avec des dettes ou des litiges sociaux cachés, ou utiliser une structure qui ne résistera pas à un contrôle. Nous les examinons tôt, pour que vous puissiez renégocier ou renoncer.",
    fallbackTitle="Ce que nous vérifions avant la signature",
    fallbacks=["La durée du bail, les clauses de sortie et qui est responsable des licences",
               "Le zonage et l'usage autorisé des locaux",
               "La société, les dettes, la situation fiscale et les dossiers du personnel d'un bar que vous rachetez",
               "Si votre concept est licite avec les licences disponibles",
               "Un calendrier et un budget réalistes pour les licences et le personnel"],
    stages=[("Conseil sur la structure et la faisabilité :", "Une recommandation écrite sur la propriété, le capital et les autorisations."),
            ("Revue des locaux et du bail :", "Vérifications et points de négociation avant de vous engager dans un bail."),
            ("Société et licences :", "Immatriculation de la société et de l'activité, et demandes de licences."),
            ("Personnel et permis de travail :", "Contrats de travail, demandes de permis de travail et procédures de conformité."),
            ("Suivi continu :", "Renouvellements, contrôles et questions sociales après l'ouverture.")],
    faq=[("Un étranger peut-il détenir 100 % d'un bar en Thaïlande ?", "Les activités de service comme les bars sont en principe limitées pour la détention majoritaire étrangère par la loi sur les activités des étrangers, sauf licence ou autre autorisation. Nous expliquons ce qui est réaliste pour votre concept et quelles structures sont licites."),
         ("Un actionnaire prête-nom thaïlandais est-il possible ?", "Non. Utiliser des prête-noms pour détenir des actions pour le compte d'un étranger est illicite et fait l'objet de contrôles actuels. Nous ne recommandons ni ne mettons en place de tels montages."),
         ("Pouvez-vous m'aider à racheter un bar existant ?", "Oui. Nous vérifions la société, le bail, les licences, les dettes, les dossiers du personnel et la situation fiscale avant que vous payiez, et nous vous conseillons sur la structure de l'achat."),
         ("Comment engager le personnel d'animation ?", "Cela dépend de la réalité de la relation de travail. Certaines personnes sont salariées, et les traiter comme des indépendantes pour éviter les obligations crée un risque. Nous examinons l'arrangement réel et vous conseillons sur les options licites."),
         ("Pouvez-vous me représenter auprès des autorités de Pattaya ?", "Nous vous assistons pour les demandes, les contrôles et les renouvellements à Pattaya et à Chonburi, et vous indiquons ce que chaque autorité exige.")],
)

C['zh'] = dict(
    title="芭堤雅酒吧与娱乐场所设立及许可 | 瓦莱拉克律师事务所",
    description="为在芭堤雅开设或收购酒吧、餐厅和娱乐场所的外国投资者提供法律服务：合法公司结构、外资持股、酒类及场所许可证、员工与工作许可，以英文说明。",
    eyebrow="酒店餐饮与娱乐",
    h1="芭堤雅酒吧与娱乐场所设立及许可",
    lead="为在芭堤雅和春武里府开设或收购酒吧、餐厅或娱乐场所的外国投资者提供公司结构、许可证、场地核查及员工规则方面的支持。",
    introEyebrow="场所业主与投资者",
    introTitle="开业前先把结构和许可证理顺",
    intro="酒吧或娱乐场所涉及多套规则：外资持股限制、酒类与娱乐的地方许可、土地分区与建筑用途、雇佣与工作许可要求，以及税务。针对名义股东结构的执法正在加强，结构不当的场所可能被吊销许可证或被关闭。瓦莱拉克律师事务所协助您选择合法的结构，在您签署租约之前核查场地，指导许可证和各类许可，并搭建员工与合同框架，让业务得以持续经营。我们提供法律和监管合规方面的建议，不会推荐掩盖外资持股的安排。",
    situations=["计划在芭堤雅或中天开设酒吧、餐厅或现场音乐场所的外国投资者",
                "收购现有酒吧、需要先核查公司、租约、许可证和债务的买家",
                "希望增加音乐、DJ活动或延长营业时间的商家",
                "不确定如何合法聘用经理、调酒师和娱乐员工的业主",
                "正面临检查、许可证续期或劳动投诉的现有场所"],
    reviewTitle="我们能提供的协助",
    reviewIntro="我们涵盖场所必须做好的主要法律领域。",
    cards=[("持股与结构", "服务业的外资多数持股受到限制。我们说明合法的选择，例如外国人经营业务许可证或其他批准，以及为什么名义股东是法律风险和执法风险。"),
           ("场地与分区", "该建筑和地点能否合法用作酒吧或娱乐场所，以及租约中的关键条款。"),
           ("许可证", "酒类销售许可证、娱乐场所许可证、营业登记，以及适用时的音乐和表演许可。"),
           ("员工与工作许可", "外籍经理的工作许可、通常适用的泰籍员工配置要求及其达成方式，以及劳动合同。"),
           ("外包人员、佣金与社保", "员工究竟是雇员还是真正的独立承包人、佣金安排、税务和社会保险。"),
           ("检查与合规", "为检查、续期和投诉做好准备，以及与芭堤雅和春武里府有关部门打交道。")],
    noEyebrow="作出承诺之前",
    noTitle="签租约之前先核查场地和结构",
    noText="最昂贵的错误往往发生在开业之前：就无法获得许可的场地签下长期租约、收购带有隐藏债务或劳动索赔的酒吧，或采用经不起检查的结构。我们会尽早处理这些问题，让您可以重新谈判或及时退出。",
    fallbackTitle="签约前我们核查的事项",
    fallbacks=["租期、解约条款，以及由谁负责许可证",
               "场地的分区和建筑用途状态",
               "您拟收购酒吧的公司、债务、税务和员工记录",
               "您的经营概念在现有许可证下是否合法",
               "许可证和员工配置的现实时间表与预算"],
    stages=[("结构与可行性建议：", "关于持股、资本和审批的书面建议。"),
            ("场地与租约审查：", "在您签署租约之前的核查和谈判要点。"),
            ("公司与许可证：", "公司注册、营业登记和许可证申请。"),
            ("员工与工作许可：", "劳动合同、工作许可申请及合规流程。"),
            ("持续支持：", "开业后的续期、检查及劳动事务。")],
    faq=[("外国人可以100%持有泰国的酒吧吗？", "根据《外国人经营业务法》，酒吧等服务业一般限制外资多数持股，除非适用许可证或其他批准。我们会说明什么对您的经营概念是现实的，以及哪些结构是合法的。"),
         ("可以使用泰国名义股东吗？", "不可以。使用名义股东替外国人持股是违法的，也是当前执法的重点。我们不推荐也不设立此类安排。"),
         ("你们能帮我收购现有酒吧吗？", "可以。我们会在您付款之前核查公司、租约、许可证、债务、员工记录和税务状况，并就收购结构提出建议。"),
         ("娱乐员工应当如何聘用？", "这取决于实际的工作关系。有些人是雇员，为了逃避义务而把他们当作自由职业者会带来风险。我们会审视实际安排，并就合法的选择提供建议。"),
         ("你们能代表我与芭堤雅的有关部门打交道吗？", "我们协助在芭堤雅和春武里府办理申请、检查和续期，并告知各部门的要求。")],
)

PAGE = dict(
    slug='pattaya-bar-entertainment-venue-licensing',
    heroimg='company-registration-lawyer.webp',
    practice='company-registration-services',
    icons=['ti-building', 'ti-map-pin', 'ti-license', 'ti-id-badge', 'ti-users', 'ti-clipboard-check'],
    related=['company-registration-services', 'pattaya-company-registration-business-licensing', 'visa-work-permit',
             'pattaya-law-office'],
    topic='company',
    C=C,
)
