"""Labour disputes and employment claims in Thailand."""

C = {}

C['en'] = dict(
    title="Labour Disputes & Employment Claims in Thailand | Walailak Law Firm",
    description="Help for employees and employers with unpaid wages, termination, severance, labour department complaints and Labour Court claims in Thailand, in English.",
    eyebrow="EMPLOYMENT DISPUTES",
    h1="Labour Disputes & Employment Claims in Thailand",
    lead="English-language advice for foreign employees and for employers on dismissal, severance, unpaid wages and complaints to the labour authorities.",
    introEyebrow="Employees and employers",
    introTitle="Choose the right route before time runs out",
    intro="Thai labour law protects employees through minimum standards on wages, working hours, leave and severance pay, and disputes can be taken to the labour authorities or to the Labour Court. These rules apply to many foreign workers as well, and employers carry their own risks if an employee is dismissed or a contract is ended incorrectly. Walailak Law Firm reviews the contract, the evidence and what has already been filed, explains the options in English, and acts for either the worker or the employer. Where a complaint to the labour department has stalled, we look at whether to push it, change route or take the claim to court.",
    situations=["Unpaid wages, overtime or bonuses",
                "Dismissal without notice or severance, or a termination you want to challenge",
                "A complaint to the labour department that has had no response",
                "An employer facing a claim from a current or former employee",
                "A dispute that also affects a work permit or a foreign employee's visa"],
    reviewTitle="What we cover",
    reviewIntro="We advise on the claim itself and on the route that suits your goal.",
    cards=[("Wages and overtime", "Unpaid wages, overtime, holiday pay and bonuses, and what the contract and records show."),
           ("Termination and notice", "Whether a termination was lawful and what notice or compensation applies."),
           ("Severance pay", "Severance is generally based on length of service and applies in many dismissals, with exceptions for certain serious misconduct."),
           ("Labour department complaints", "Preparing a complaint to the labour protection officer and following it up, including when there has been no response."),
           ("Labour Court claims", "Filing, evidence and hearings. The court process is designed to be accessible but still needs careful preparation."),
           ("Advice for employers", "Employment contracts, disciplinary steps and dismissals handled correctly, and responding to claims.")],
    noEyebrow="Choosing the route",
    noTitle="The right route depends on the facts",
    noText="A labour department complaint is quicker and cheaper but may not settle a contested case. A court claim gives a binding result but takes longer. We explain which route fits your goal, the evidence you need and what to do while you wait for a response.",
    fallbackTitle="What we gather first",
    fallbacks=["The employment contract, payslips and records of hours and payments",
               "Messages, notices and any termination letter",
               "Your work permit and visa status, which can limit your options",
               "What has already been filed and any replies",
               "Your goal: payment, reinstatement or a negotiated exit"],
    stages=[("Case review:", "Documents and a written view of your position and options."),
            ("Demand letter or negotiation:", "A formal demand and talks with the other side."),
            ("Labour department complaint:", "Preparing and following up the complaint."),
            ("Labour Court claim:", "Filing and running the claim if the matter is not resolved."),
            ("Work permit follow-up:", "Dealing with the work permit and visa consequences of the dispute.")],
    faq=[("Can foreign employees use Thai labour law protections?", "Generally yes, if they work in Thailand. Whether a particular right applies depends on the contract, the type of work and the facts."),
         ("My labour department complaint has had no response. What now?", "We review what was filed and the evidence, follow up with the officer, and advise whether to escalate or take the claim to the Labour Court."),
         ("Am I entitled to severance pay?", "Severance is generally based on length of service and applies to many dismissals, with exceptions for certain serious misconduct. We check your contract and the reason for termination."),
         ("Do you act for employers?", "Yes. We advise on employment contracts, lawful termination and defending claims."),
         ("How long do I have to act?", "Time limits apply to employment claims and can be short, so contact us as soon as possible and keep all your documents.")],
)

C['th'] = dict(
    title="ข้อพิพาทแรงงานและการเรียกร้องด้านการจ้างงานในประเทศไทย | สำนักงานกฎหมายวลัยลักษณ์",
    description="ความช่วยเหลือสำหรับลูกจ้างและนายจ้างเรื่องค่าจ้างค้างจ่าย การเลิกจ้าง ค่าชดเชย การร้องเรียนต่อสำนักงานแรงงาน และการฟ้องศาลแรงงานในไทย เป็นภาษาอังกฤษ",
    eyebrow="ข้อพิพาทด้านการจ้างงาน",
    h1="ข้อพิพาทแรงงานและการเรียกร้องด้านการจ้างงานในประเทศไทย",
    lead="คำปรึกษาเป็นภาษาอังกฤษสำหรับลูกจ้างชาวต่างชาติและนายจ้าง เรื่องการเลิกจ้าง ค่าชดเชย ค่าจ้างค้างจ่าย และการร้องเรียนต่อหน่วยงานด้านแรงงาน",
    introEyebrow="ลูกจ้างและนายจ้าง",
    introTitle="เลือกช่องทางที่ถูกต้องก่อนหมดเวลา",
    intro="กฎหมายแรงงานไทยคุ้มครองลูกจ้างด้วยมาตรฐานขั้นต่ำเรื่องค่าจ้าง ชั่วโมงทำงาน วันลา และค่าชดเชย และข้อพิพาทสามารถนำไปสู่หน่วยงานด้านแรงงานหรือศาลแรงงานได้ กฎเหล่านี้ใช้กับแรงงานต่างชาติจำนวนมากด้วย และนายจ้างก็มีความเสี่ยงของตนเองหากเลิกจ้างหรือสิ้นสุดสัญญาอย่างไม่ถูกต้อง สำนักงานกฎหมายวลัยลักษณ์ตรวจสอบสัญญา พยานหลักฐาน และสิ่งที่ยื่นไปแล้ว อธิบายทางเลือกเป็นภาษาอังกฤษ และดำเนินการให้ทั้งฝ่ายลูกจ้างหรือนายจ้าง หากข้อร้องเรียนต่อสำนักงานแรงงานหยุดชะงัก เราพิจารณาว่าควรติดตามต่อ เปลี่ยนช่องทาง หรือนำคดีขึ้นสู่ศาล",
    situations=["ค่าจ้าง ค่าล่วงเวลา หรือโบนัสค้างจ่าย",
                "การเลิกจ้างโดยไม่บอกกล่าวล่วงหน้าหรือไม่จ่ายค่าชดเชย หรือการเลิกจ้างที่คุณต้องการโต้แย้ง",
                "ข้อร้องเรียนต่อสำนักงานแรงงานที่ยังไม่มีการตอบกลับ",
                "นายจ้างที่ถูกลูกจ้างปัจจุบันหรืออดีตลูกจ้างเรียกร้อง",
                "ข้อพิพาทที่กระทบใบอนุญาตทำงานหรือวีซ่าของลูกจ้างต่างชาติด้วย"],
    reviewTitle="สิ่งที่เราครอบคลุม",
    reviewIntro="เราให้คำปรึกษาทั้งเรื่องข้อเรียกร้องและช่องทางที่เหมาะกับเป้าหมายของคุณ",
    cards=[("ค่าจ้างและค่าล่วงเวลา", "ค่าจ้าง ค่าล่วงเวลา ค่าจ้างวันหยุด และโบนัสที่ค้างจ่าย และสิ่งที่สัญญากับบันทึกแสดง"),
           ("การเลิกจ้างและการบอกกล่าว", "การเลิกจ้างชอบด้วยกฎหมายหรือไม่ และต้องบอกกล่าวหรือจ่ายค่าตอบแทนอย่างไร"),
           ("ค่าชดเชย", "ค่าชดเชยโดยทั่วไปคำนวณตามอายุงานและใช้กับการเลิกจ้างหลายกรณี ยกเว้นกรณีกระทำผิดร้ายแรงบางประการ"),
           ("การร้องเรียนต่อสำนักงานแรงงาน", "จัดทำคำร้องต่อพนักงานตรวจแรงงานและติดตามผล รวมถึงเมื่อไม่มีการตอบกลับ"),
           ("การฟ้องศาลแรงงาน", "การยื่นฟ้อง พยานหลักฐาน และการพิจารณา กระบวนการของศาลออกแบบให้เข้าถึงได้ แต่ยังต้องเตรียมการอย่างรอบคอบ"),
           ("คำปรึกษาสำหรับนายจ้าง", "สัญญาจ้าง ขั้นตอนทางวินัย และการเลิกจ้างที่ทำอย่างถูกต้อง และการตอบข้อเรียกร้อง")],
    noEyebrow="การเลือกช่องทาง",
    noTitle="ช่องทางที่เหมาะสมขึ้นกับข้อเท็จจริง",
    noText="การร้องเรียนต่อสำนักงานแรงงานเร็วกว่าและประหยัดกว่า แต่อาจไม่ยุติข้อพิพาทที่มีการโต้แย้ง ส่วนการฟ้องศาลให้ผลผูกพันแต่ใช้เวลานานกว่า เราอธิบายว่าช่องทางใดเหมาะกับเป้าหมายของคุณ พยานหลักฐานที่ต้องมี และสิ่งที่ควรทำระหว่างรอการตอบกลับ",
    fallbackTitle="สิ่งที่เรารวบรวมก่อน",
    fallbacks=["สัญญาจ้าง สลิปเงินเดือน และบันทึกชั่วโมงทำงานและการจ่ายเงิน",
               "ข้อความ หนังสือแจ้ง และหนังสือเลิกจ้าง (ถ้ามี)",
               "สถานะใบอนุญาตทำงานและวีซ่าของคุณ ซึ่งอาจจำกัดทางเลือก",
               "สิ่งที่ยื่นไปแล้วและคำตอบที่ได้รับ",
               "เป้าหมายของคุณ: การจ่ายเงิน การกลับเข้าทำงาน หรือการออกจากงานโดยตกลงกัน"],
    stages=[("ตรวจสอบคดี:", "เอกสารและความเห็นเป็นลายลักษณ์อักษรเกี่ยวกับสถานะและทางเลือกของคุณ"),
            ("หนังสือทวงถามหรือการเจรจา:", "หนังสือทวงถามอย่างเป็นทางการและการเจรจากับอีกฝ่าย"),
            ("ร้องเรียนต่อสำนักงานแรงงาน:", "จัดทำและติดตามคำร้อง"),
            ("ฟ้องศาลแรงงาน:", "ยื่นและดำเนินคดีหากเรื่องไม่ยุติ"),
            ("ติดตามเรื่องใบอนุญาตทำงาน:", "จัดการผลกระทบต่อใบอนุญาตทำงานและวีซ่าจากข้อพิพาท")],
    faq=[("ลูกจ้างต่างชาติใช้ความคุ้มครองตามกฎหมายแรงงานไทยได้หรือไม่?", "โดยทั่วไปได้ หากทำงานในประเทศไทย สิทธิแต่ละอย่างจะใช้ได้หรือไม่ขึ้นกับสัญญา ประเภทงาน และข้อเท็จจริง"),
         ("ข้อร้องเรียนต่อสำนักงานแรงงานของฉันไม่มีการตอบกลับ ต้องทำอย่างไร?", "เราตรวจสอบสิ่งที่ยื่นและพยานหลักฐาน ติดตามกับเจ้าหน้าที่ และแนะนำว่าควรยกระดับหรือนำคดีขึ้นสู่ศาลแรงงาน"),
         ("ฉันมีสิทธิได้รับค่าชดเชยหรือไม่?", "ค่าชดเชยโดยทั่วไปคำนวณตามอายุงานและใช้กับการเลิกจ้างหลายกรณี ยกเว้นกรณีกระทำผิดร้ายแรงบางประการ เราตรวจสัญญาและเหตุผลในการเลิกจ้างของคุณ"),
         ("ดำเนินการให้นายจ้างด้วยหรือไม่?", "ได้ เราให้คำปรึกษาเรื่องสัญญาจ้าง การเลิกจ้างที่ชอบด้วยกฎหมาย และการต่อสู้ข้อเรียกร้อง"),
         ("มีเวลานานเท่าใดในการดำเนินการ?", "ข้อเรียกร้องด้านการจ้างงานมีอายุความซึ่งอาจสั้น จึงควรติดต่อเราโดยเร็วและเก็บเอกสารทั้งหมดไว้")],
)

C['fr'] = dict(
    title="Litiges du Travail et Réclamations Salariales en Thaïlande | Walailak Law Firm",
    description="Aide aux salariés et employeurs : salaires impayés, licenciement, indemnités, plainte au service du travail et tribunal du travail en Thaïlande, en anglais.",
    eyebrow="LITIGES DU TRAVAIL",
    h1="Litiges du Travail et Réclamations Salariales en Thaïlande",
    lead="Des conseils en anglais pour les salariés étrangers et pour les employeurs sur le licenciement, les indemnités, les salaires impayés et les plaintes auprès des autorités du travail.",
    introEyebrow="Salariés et employeurs",
    introTitle="Choisir la bonne voie avant l'expiration des délais",
    intro="Le droit du travail thaïlandais protège les salariés par des normes minimales sur le salaire, la durée du travail, les congés et l'indemnité de licenciement, et les litiges peuvent être portés devant les autorités du travail ou le tribunal du travail. Ces règles s'appliquent aussi à de nombreux travailleurs étrangers, et les employeurs courent leurs propres risques si un salarié est licencié ou si un contrat est rompu de façon incorrecte. Walailak Law Firm examine le contrat, les preuves et ce qui a déjà été déposé, explique les options en anglais et agit pour le salarié comme pour l'employeur. Lorsqu'une plainte auprès du service du travail est restée sans suite, nous examinons s'il faut la relancer, changer de voie ou saisir le tribunal.",
    situations=["Des salaires, des heures supplémentaires ou des primes impayés",
                "Un licenciement sans préavis ni indemnité, ou une rupture que vous voulez contester",
                "Une plainte auprès du service du travail restée sans réponse",
                "Un employeur visé par la réclamation d'un salarié actuel ou ancien",
                "Un litige qui touche aussi le permis de travail ou le visa d'un salarié étranger"],
    reviewTitle="Ce que nous couvrons",
    reviewIntro="Nous conseillons sur la demande elle-même et sur la voie qui convient à votre objectif.",
    cards=[("Salaires et heures supplémentaires", "Salaires, heures supplémentaires, congés payés et primes impayés, et ce que montrent le contrat et les documents."),
           ("Rupture et préavis", "La rupture était-elle licite, et quel préavis ou quelle indemnité s'applique."),
           ("Indemnité de licenciement", "L'indemnité est en général fonction de l'ancienneté et s'applique dans de nombreux licenciements, avec des exceptions pour certaines fautes graves."),
           ("Plaintes au service du travail", "La préparation d'une plainte auprès de l'inspecteur du travail et son suivi, y compris en l'absence de réponse."),
           ("Actions devant le tribunal du travail", "Le dépôt, les preuves et les audiences. La procédure est conçue pour être accessible mais exige une préparation soignée."),
           ("Conseils aux employeurs", "Contrats de travail, mesures disciplinaires et licenciements conduits correctement, et réponse aux réclamations.")],
    noEyebrow="Choisir la voie",
    noTitle="La bonne voie dépend des faits",
    noText="Une plainte au service du travail est plus rapide et moins coûteuse, mais elle ne règle pas forcément un dossier contesté. Une action en justice donne un résultat contraignant mais prend plus de temps. Nous expliquons quelle voie correspond à votre objectif, les preuves nécessaires et ce qu'il faut faire en attendant une réponse.",
    fallbackTitle="Ce que nous rassemblons d'abord",
    fallbacks=["Le contrat de travail, les bulletins de paie et les relevés d'heures et de paiements",
               "Les messages, avis et toute lettre de licenciement",
               "Votre permis de travail et votre visa, qui peuvent limiter vos options",
               "Ce qui a déjà été déposé et les réponses reçues",
               "Votre objectif : paiement, réintégration ou départ négocié"],
    stages=[("Examen du dossier :", "Les documents et un avis écrit sur votre situation et vos options."),
            ("Mise en demeure ou négociation :", "Une demande formelle et des discussions avec l'autre partie."),
            ("Plainte au service du travail :", "Préparation et suivi de la plainte."),
            ("Action devant le tribunal du travail :", "Dépôt et conduite de l'action si le litige n'est pas résolu."),
            ("Suivi du permis de travail :", "Traitement des conséquences du litige sur le permis de travail et le visa.")],
    faq=[("Les salariés étrangers peuvent-ils invoquer le droit du travail thaïlandais ?", "En général oui, s'ils travaillent en Thaïlande. L'application d'un droit précis dépend du contrat, du type de travail et des faits."),
         ("Ma plainte au service du travail est restée sans réponse. Que faire ?", "Nous examinons ce qui a été déposé et les preuves, relançons l'agent, et conseillons de remonter le dossier ou de saisir le tribunal du travail."),
         ("Ai-je droit à une indemnité de licenciement ?", "L'indemnité est en général fonction de l'ancienneté et concerne de nombreux licenciements, avec des exceptions pour certaines fautes graves. Nous vérifions votre contrat et le motif de la rupture."),
         ("Agissez-vous pour les employeurs ?", "Oui. Nous conseillons sur les contrats de travail, la rupture licite et la défense face aux réclamations."),
         ("De combien de temps dispose-je pour agir ?", "Des délais s'appliquent aux réclamations salariales et peuvent être courts : contactez-nous au plus vite et conservez tous vos documents.")],
)

C['zh'] = dict(
    title="泰国劳动争议与雇佣索赔 | 瓦莱拉克律师事务所",
    description="为外籍雇员和雇主提供英文协助：拖欠工资、解雇、遣散费、向劳工部门投诉及泰国劳工法院索赔，说明可行途径、所需证据与时效。",
    eyebrow="雇佣争议",
    h1="泰国劳动争议与雇佣索赔",
    lead="为外籍雇员和雇主提供英文咨询，涉及解雇、遣散费、拖欠工资以及向劳工部门投诉。",
    introEyebrow="雇员与雇主",
    introTitle="在时效届满之前选对途径",
    intro="泰国劳动法通过工资、工作时间、休假和遣散费方面的最低标准保护雇员，争议可以提交劳工部门或劳工法院处理。这些规则同样适用于许多外籍员工，而雇主若错误地解雇员工或终止合同，也要承担自身的风险。瓦莱拉克律师事务所审阅合同、证据以及已经提交的材料，用英文说明各种选择，并可代表员工或雇主行事。当向劳工部门提出的投诉停滞不前时，我们会评估是继续跟进、改变途径，还是将索赔提交法院。",
    situations=["拖欠的工资、加班费或奖金",
                "未经通知或未支付遣散费的解雇，或您想要质疑的终止",
                "向劳工部门投诉后一直没有回应",
                "雇主面对现任或前任员工的索赔",
                "同时影响外籍员工工作许可或签证的争议"],
    reviewTitle="我们涵盖的内容",
    reviewIntro="我们既就索赔本身提供建议，也就适合您目标的途径提供建议。",
    cards=[("工资与加班费", "拖欠的工资、加班费、假日工资和奖金，以及合同和记录所显示的内容。"),
           ("解雇与通知", "解雇是否合法，以及适用何种通知期或补偿。"),
           ("遣散费", "遣散费通常按工龄计算，适用于许多解雇情形，但某些严重不当行为除外。"),
           ("向劳工部门投诉", "向劳动保护官员准备并跟进投诉，包括没有回应时的处理。"),
           ("劳工法院索赔", "起诉、证据和开庭。法院程序设计得较为便利，但仍需认真准备。"),
           ("面向雇主的建议", "劳动合同、纪律措施和正确处理的解雇，以及应对索赔。")],
    noEyebrow="选择途径",
    noTitle="合适的途径取决于事实",
    noText="向劳工部门投诉更快也更省钱，但未必能解决有争议的案件。提起诉讼可以得到有约束力的结果，但耗时更长。我们会说明哪种途径适合您的目标、需要哪些证据，以及在等待回应期间应当做什么。",
    fallbackTitle="我们首先收集的材料",
    fallbacks=["劳动合同、工资单以及工时和付款记录",
               "信息、通知和任何解雇通知书",
               "您的工作许可和签证状态，这可能限制您的选择",
               "已经提交的材料及收到的回复",
               "您的目标：获得付款、恢复工作，还是协商离职"],
    stages=[("案件审查：", "审阅文件，并就您的立场和选择出具书面意见。"),
            ("索赔函或谈判：", "正式的索赔函以及与对方的谈判。"),
            ("向劳工部门投诉：", "准备并跟进投诉。"),
            ("劳工法院索赔：", "如争议未能解决，则提起并办理索赔。"),
            ("工作许可跟进：", "处理争议对工作许可和签证造成的后果。")],
    faq=[("外籍员工可以适用泰国劳动法的保护吗？", "一般可以，只要在泰国工作。具体某项权利是否适用，取决于合同、工作类型和事实。"),
         ("我向劳工部门的投诉一直没有回应，怎么办？", "我们会审阅已提交的材料和证据，向办案官员跟进，并就是否升级处理或提交劳工法院提出建议。"),
         ("我有权获得遣散费吗？", "遣散费通常按工龄计算，适用于许多解雇情形，但某些严重不当行为除外。我们会核对您的合同和终止原因。"),
         ("你们也代表雇主吗？", "是的。我们就劳动合同、合法解雇以及应对索赔提供建议。"),
         ("我有多长时间采取行动？", "雇佣索赔适用时效，期限可能很短，请尽快联系我们并保留所有文件。")],
)

PAGE = dict(
    slug='labour-disputes-employment-claims-thailand',
    heroimg='civil-litigation-lawyer.webp',
    practice='civil-litigation-services',
    icons=['ti-report-money', 'ti-clock', 'ti-coin', 'ti-mail', 'ti-gavel', 'ti-briefcase'],
    related=['civil-litigation-services', 'visa-work-permit', 'pattaya-law-office', 'rayong-law-office'],
    topic='disputes',
    C=C,
)
