"""Child legitimation in Thailand for unmarried foreign fathers."""

C = {}

C['en'] = dict(
    title="Child Legitimation in Thailand for Foreign Fathers | Walailak Law Firm",
    description="Legal support for foreign fathers legitimating a child born to an unmarried Thai mother: court petition, district registration, Kor Ror 11 and embassy papers.",
    eyebrow="FAMILY LAW",
    h1="Child Legitimation in Thailand for Foreign Fathers",
    lead="English-language support for unmarried foreign fathers who want their legal relationship with a child recognised in Thailand, from the court petition to registration at the district office.",
    introEyebrow="Unmarried foreign fathers",
    introTitle="Being named on the birth certificate may not be enough",
    intro="When the parents are not married, Thai law treats the mother as the child's legal parent from birth. A foreign father who is named on the birth certificate may still need formal legitimation so that his legal relationship with the child is recognised, for example for his embassy's civil registration, for the child's passport, or to protect his rights. Depending on the circumstances, legitimation is done either by registration at the district office with the necessary consents or by an order of the Juvenile and Family Court, followed by registration and the issue of the legitimation record (Kor Ror 11). Walailak Law Firm prepares the petition and documents, represents you through the process and helps with the paperwork your embassy asks for.",
    situations=["An unmarried couple with a child born in Thailand and a foreign father",
                "An embassy that requires Thai legitimation before it will register the child",
                "A mother who agrees, and a father who wants the process organised from start to finish",
                "A father whose paternity or rights are disputed",
                "A family planning to move abroad that needs the documents in order"],
    reviewTitle="What the process involves",
    reviewIntro="We confirm the route first, then prepare each step.",
    cards=[("Which route applies", "Registration with the necessary consents, or a court petition, depending on the child's age, the mother's consent and the facts."),
           ("Petition and evidence", "Preparing the petition and gathering the birth certificate, the parents' documents and translations."),
           ("Court hearing", "Attending the hearing, how many appearances the parents usually need, and which steps can be handled through a representative."),
           ("Registration and certificate", "Registering the result at the district office and obtaining the legitimation record (Kor Ror 11)."),
           ("Embassy and passport", "How to present the result to your embassy for civil registration and the child's passport."),
           ("Related issues", "Surname, parental rights and custody, support, and arrangements if the parents later separate.")],
    noEyebrow="Before you start",
    noTitle="Know which route applies to you",
    noText="The right route depends on whether the mother consents, whether the child is old enough to be asked, and what your embassy requires. We confirm this first so you do not file in the wrong place or miss a document. We also explain what this process does not decide: nationality, for example, depends on your home country's rules.",
    fallbackTitle="What we confirm first",
    fallbacks=["The child's age and where the birth is registered",
               "The mother's consent and whether she can attend",
               "What your embassy accepts as proof",
               "Any dispute about paternity or custody",
               "Your timeline, such as a planned move abroad"],
    stages=[("Route and document check:", "Confirming which route applies and what is needed."),
            ("Petition or registration filing:", "Preparing and filing the petition or the registration."),
            ("Court hearing:", "Representation at the Juvenile and Family Court."),
            ("Registration and certificate:", "Registration at the district office and the legitimation record."),
            ("Embassy follow-up:", "Help presenting the documents to your embassy.")],
    faq=[("Does being named on the birth certificate make me the legal father?", "Not necessarily. A father who is not married to the mother usually needs legitimation for his relationship with the child to be formally recognised."),
         ("Can legitimation be done without going to court?", "In some cases, by registration at the district office with the required consents. Where consent is missing or the child is too young to consent, a court order is usually needed. We confirm which applies."),
         ("Does the mother need to attend?", "Her consent is normally required and she is usually asked to appear or confirm it, but the exact requirements depend on the route and the court."),
         ("How long does it take?", "It depends on the route, the court's schedule and the documents. We give an estimate after reviewing your situation."),
         ("Does this give my child my nationality?", "No. Nationality depends on your home country's law. Legitimation is often a step your embassy requires before it registers the child.")],
)

C['th'] = dict(
    title="การรับรองบุตรในประเทศไทยสำหรับบิดาชาวต่างชาติ | สำนักงานกฎหมายวลัยลักษณ์",
    description="บริการกฎหมายสำหรับบิดาชาวต่างชาติที่รับรองบุตรซึ่งเกิดจากมารดาชาวไทยที่ไม่ได้สมรส: คำร้องต่อศาล การจดทะเบียนที่อำเภอ คร.11 และเอกสารสำหรับสถานทูต",
    eyebrow="กฎหมายครอบครัว",
    h1="การรับรองบุตรในประเทศไทยสำหรับบิดาชาวต่างชาติ",
    lead="บริการเป็นภาษาอังกฤษสำหรับบิดาชาวต่างชาติที่ไม่ได้สมรสและต้องการให้ความสัมพันธ์ทางกฎหมายกับบุตรได้รับการรับรองในประเทศไทย ตั้งแต่คำร้องต่อศาลจนถึงการจดทะเบียนที่อำเภอ",
    introEyebrow="บิดาชาวต่างชาติที่ไม่ได้สมรส",
    introTitle="การมีชื่อในสูติบัตรอาจยังไม่เพียงพอ",
    intro="เมื่อบิดามารดาไม่ได้สมรสกัน กฎหมายไทยถือว่ามารดาเป็นผู้ปกครองตามกฎหมายของบุตรตั้งแต่เกิด บิดาชาวต่างชาติที่มีชื่ออยู่ในสูติบัตรอาจยังต้องทำการรับรองบุตรอย่างเป็นทางการเพื่อให้ความสัมพันธ์ทางกฎหมายกับบุตรได้รับการรับรอง เช่น สำหรับการจดทะเบียนราษฎรของสถานทูต การทำหนังสือเดินทางให้บุตร หรือเพื่อคุ้มครองสิทธิของบิดา ขึ้นอยู่กับสถานการณ์ การรับรองบุตรทำได้ทั้งโดยการจดทะเบียนที่อำเภอพร้อมความยินยอมที่จำเป็น หรือโดยคำสั่งของศาลเยาวชนและครอบครัว ตามด้วยการจดทะเบียนและการออกหลักฐานการรับรองบุตร (คร.11) สำนักงานกฎหมายวลัยลักษณ์จัดทำคำร้องและเอกสาร ดำเนินการแทนคุณตลอดกระบวนการ และช่วยจัดเอกสารที่สถานทูตของคุณต้องการ",
    situations=["คู่รักที่ไม่ได้สมรสซึ่งมีบุตรเกิดในประเทศไทยและบิดาเป็นชาวต่างชาติ",
                "สถานทูตที่กำหนดให้มีการรับรองบุตรตามกฎหมายไทยก่อนจึงจะจดทะเบียนบุตรให้",
                "มารดาที่ยินยอม และบิดาที่ต้องการให้ดำเนินการตั้งแต่ต้นจนจบ",
                "บิดาที่ถูกโต้แย้งเรื่องความเป็นบิดาหรือสิทธิ",
                "ครอบครัวที่วางแผนย้ายไปต่างประเทศและต้องการให้เอกสารเรียบร้อย"],
    reviewTitle="กระบวนการเกี่ยวข้องกับอะไร",
    reviewIntro="เราตรวจสอบช่องทางก่อน แล้วจึงเตรียมแต่ละขั้นตอน",
    cards=[("ช่องทางที่ใช้กับคุณ", "การจดทะเบียนพร้อมความยินยอมที่จำเป็น หรือการยื่นคำร้องต่อศาล ขึ้นกับอายุของบุตร ความยินยอมของมารดา และข้อเท็จจริง"),
           ("คำร้องและพยานหลักฐาน", "จัดทำคำร้องและรวบรวมสูติบัตร เอกสารของบิดามารดา และคำแปล"),
           ("การพิจารณาของศาล", "การไปศาล จำนวนครั้งที่บิดามารดามักต้องไป และขั้นตอนที่ให้ตัวแทนดำเนินการแทนได้"),
           ("การจดทะเบียนและหลักฐาน", "จดทะเบียนผลที่อำเภอและขอหลักฐานการรับรองบุตร (คร.11)"),
           ("สถานทูตและหนังสือเดินทาง", "วิธีนำผลไปแสดงต่อสถานทูตเพื่อจดทะเบียนราษฎรและทำหนังสือเดินทางให้บุตร"),
           ("เรื่องที่เกี่ยวข้อง", "นามสกุล อำนาจปกครองและสิทธิในการดูแลบุตร การอุปการะเลี้ยงดู และการจัดการหากบิดามารดาแยกกันในภายหลัง")],
    noEyebrow="ก่อนเริ่มต้น",
    noTitle="รู้ว่าช่องทางใดใช้กับคุณ",
    noText="ช่องทางที่เหมาะสมขึ้นกับว่ามารดายินยอมหรือไม่ บุตรโตพอที่จะให้ความเห็นหรือไม่ และสถานทูตของคุณต้องการอะไร เราตรวจสอบเรื่องนี้ก่อนเพื่อไม่ให้คุณยื่นผิดที่หรือขาดเอกสาร และเราอธิบายด้วยว่ากระบวนการนี้ไม่ได้ตัดสินเรื่องใด เช่น สัญชาติซึ่งขึ้นกับกฎหมายของประเทศคุณ",
    fallbackTitle="สิ่งที่เราตรวจสอบก่อน",
    fallbacks=["อายุของบุตรและที่จดทะเบียนการเกิด",
               "ความยินยอมของมารดาและความสามารถในการไปด้วย",
               "สิ่งที่สถานทูตของคุณยอมรับเป็นหลักฐาน",
               "ข้อพิพาทเรื่องความเป็นบิดาหรืออำนาจปกครอง (ถ้ามี)",
               "กรอบเวลาของคุณ เช่น แผนย้ายไปต่างประเทศ"],
    stages=[("ตรวจช่องทางและเอกสาร:", "ยืนยันว่าช่องทางใดใช้ได้และต้องใช้อะไรบ้าง"),
            ("ยื่นคำร้องหรือจดทะเบียน:", "จัดทำและยื่นคำร้องหรือการจดทะเบียน"),
            ("การพิจารณาของศาล:", "ดำเนินการแทนที่ศาลเยาวชนและครอบครัว"),
            ("การจดทะเบียนและหลักฐาน:", "จดทะเบียนที่อำเภอและออกหลักฐานการรับรองบุตร"),
            ("ติดตามกับสถานทูต:", "ช่วยนำเอกสารไปแสดงต่อสถานทูตของคุณ")],
    faq=[("การมีชื่อในสูติบัตรทำให้ฉันเป็นบิดาตามกฎหมายหรือไม่?", "ไม่เสมอไป บิดาที่ไม่ได้สมรสกับมารดามักต้องรับรองบุตรจึงจะมีความสัมพันธ์กับบุตรที่ได้รับการรับรองอย่างเป็นทางการ"),
         ("รับรองบุตรโดยไม่ต้องไปศาลได้หรือไม่?", "ได้ในบางกรณี โดยจดทะเบียนที่อำเภอพร้อมความยินยอมที่จำเป็น หากไม่มีความยินยอมหรือบุตรยังเล็กเกินกว่าจะให้ความยินยอม มักต้องมีคำสั่งศาล เรายืนยันให้ว่ากรณีของคุณเป็นอย่างไร"),
         ("มารดาต้องไปด้วยหรือไม่?", "โดยปกติต้องมีความยินยอมของมารดา และมักถูกเรียกให้มาแสดงตนหรือยืนยัน แต่ข้อกำหนดที่แน่นอนขึ้นกับช่องทางและศาล"),
         ("ใช้เวลานานเท่าใด?", "ขึ้นกับช่องทาง ตารางของศาล และเอกสาร เราให้ประมาณการหลังตรวจสอบสถานการณ์ของคุณ"),
         ("การรับรองบุตรทำให้บุตรได้สัญชาติของฉันหรือไม่?", "ไม่ สัญชาติขึ้นกับกฎหมายของประเทศคุณ การรับรองบุตรมักเป็นขั้นตอนที่สถานทูตของคุณกำหนดก่อนจะจดทะเบียนบุตร")],
)

C['fr'] = dict(
    title="Légitimation d'un Enfant en Thaïlande pour les Pères Étrangers | Walailak Law Firm",
    description="Accompagnement des pères étrangers pour légitimer un enfant né d'une mère thaïlandaise non mariée : requête, enregistrement, Kor Ror 11, documents d'ambassade.",
    eyebrow="DROIT DE LA FAMILLE",
    h1="Légitimation d'un Enfant en Thaïlande pour les Pères Étrangers",
    lead="Un accompagnement en anglais pour les pères étrangers non mariés qui souhaitent faire reconnaître en Thaïlande leur lien juridique avec leur enfant, de la requête au tribunal à l'enregistrement au bureau du district.",
    introEyebrow="Pères étrangers non mariés",
    introTitle="Figurer sur l'acte de naissance peut ne pas suffire",
    intro="Lorsque les parents ne sont pas mariés, le droit thaïlandais considère la mère comme le parent légal de l'enfant dès la naissance. Un père étranger qui figure sur l'acte de naissance peut néanmoins devoir procéder à une légitimation formelle pour que son lien juridique avec l'enfant soit reconnu, par exemple pour l'état civil de son ambassade, pour le passeport de l'enfant ou pour protéger ses droits. Selon les circonstances, la légitimation se fait soit par un enregistrement au bureau du district avec les consentements nécessaires, soit par une décision du tribunal pour mineurs et affaires familiales, suivie de l'enregistrement et de la délivrance du document de légitimation (Kor Ror 11). Walailak Law Firm prépare la requête et les documents, vous représente durant la procédure et vous aide pour les formalités demandées par votre ambassade.",
    situations=["Un couple non marié avec un enfant né en Thaïlande et un père étranger",
                "Une ambassade qui exige une légitimation thaïlandaise avant d'enregistrer l'enfant",
                "Une mère d'accord, et un père qui veut que la procédure soit organisée de bout en bout",
                "Un père dont la paternité ou les droits sont contestés",
                "Une famille qui prévoit de partir à l'étranger et veut ses documents en règle"],
    reviewTitle="Ce que comporte la procédure",
    reviewIntro="Nous confirmons d'abord la voie à suivre, puis préparons chaque étape.",
    cards=[("Quelle voie s'applique", "Un enregistrement avec les consentements nécessaires, ou une requête au tribunal, selon l'âge de l'enfant, le consentement de la mère et les faits."),
           ("Requête et preuves", "La préparation de la requête et la réunion de l'acte de naissance, des documents des parents et des traductions."),
           ("Audience", "La présence à l'audience, le nombre de comparutions habituellement nécessaires pour les parents et les étapes qui peuvent être traitées par un représentant."),
           ("Enregistrement et certificat", "L'enregistrement de la décision au bureau du district et l'obtention du document de légitimation (Kor Ror 11)."),
           ("Ambassade et passeport", "La manière de présenter le résultat à votre ambassade pour l'état civil et le passeport de l'enfant."),
           ("Questions connexes", "Le nom de famille, l'autorité parentale et la garde, la pension, et les arrangements si les parents se séparent plus tard.")],
    noEyebrow="Avant de commencer",
    noTitle="Savoir quelle voie s'applique à vous",
    noText="La bonne voie dépend du consentement de la mère, de l'âge de l'enfant et de ce que votre ambassade exige. Nous le confirmons d'abord pour que vous ne déposiez pas au mauvais endroit et ne manquiez aucun document. Nous expliquons aussi ce que cette procédure ne tranche pas : la nationalité, par exemple, dépend des règles de votre pays d'origine.",
    fallbackTitle="Ce que nous confirmons d'abord",
    fallbacks=["L'âge de l'enfant et le lieu d'enregistrement de la naissance",
               "Le consentement de la mère et sa possibilité de se présenter",
               "Ce que votre ambassade accepte comme preuve",
               "Tout litige sur la paternité ou la garde",
               "Votre calendrier, par exemple un départ prévu à l'étranger"],
    stages=[("Vérification de la voie et des documents :", "Confirmer quelle voie s'applique et ce qui est nécessaire."),
            ("Dépôt de la requête ou de l'enregistrement :", "Préparation et dépôt de la requête ou de l'enregistrement."),
            ("Audience :", "Représentation devant le tribunal pour mineurs et affaires familiales."),
            ("Enregistrement et certificat :", "Enregistrement au bureau du district et délivrance du document de légitimation."),
            ("Suivi auprès de l'ambassade :", "Aide pour présenter les documents à votre ambassade.")],
    faq=[("Figurer sur l'acte de naissance fait-il de moi le père légal ?", "Pas nécessairement. Un père qui n'est pas marié avec la mère a généralement besoin d'une légitimation pour que son lien avec l'enfant soit formellement reconnu."),
         ("La légitimation peut-elle se faire sans aller au tribunal ?", "Dans certains cas, par un enregistrement au bureau du district avec les consentements requis. Lorsque le consentement manque ou que l'enfant est trop jeune pour consentir, une décision de justice est généralement nécessaire. Nous confirmons laquelle s'applique."),
         ("La mère doit-elle se présenter ?", "Son consentement est normalement requis et elle est généralement invitée à comparaître ou à le confirmer, mais les exigences exactes dépendent de la voie et du tribunal."),
         ("Combien de temps cela prend-il ?", "Cela dépend de la voie, du calendrier du tribunal et des documents. Nous donnons une estimation après avoir examiné votre situation."),
         ("Cela donne-t-il ma nationalité à mon enfant ?", "Non. La nationalité dépend de la loi de votre pays d'origine. La légitimation est souvent une étape que votre ambassade exige avant d'enregistrer l'enfant.")],
)

C['zh'] = dict(
    title="外国父亲在泰国对子女的认领（婚生化） | 瓦莱拉克律师事务所",
    description="为外国父亲认领未婚泰国母亲所生子女提供法律支持：法院申请、县政府登记、Kor Ror 11及使馆所需文件，以英文说明流程并协助办理。",
    eyebrow="家事法律",
    h1="外国父亲在泰国对子女的认领",
    lead="为希望在泰国使其与子女的法律关系得到承认的未婚外国父亲提供英文支持，从向法院申请到在县政府办理登记。",
    introEyebrow="未婚外国父亲",
    introTitle="出生证明上有您的名字，可能还不够",
    intro="父母未婚时，泰国法律自子女出生起就将母亲视为子女的法定父母。出生证明上写有姓名的外国父亲，仍可能需要办理正式的认领，才能使其与子女的法律关系得到承认，例如用于使馆的民事登记、子女的护照，或保护其自身权利。视具体情况，认领可以通过在县政府凭必要的同意办理登记，或通过少年及家事法院的裁定完成，随后办理登记并取得认领记录（Kor Ror 11）。瓦莱拉克律师事务所为您准备申请书和文件，在整个过程中代表您，并协助办理您的使馆所要求的手续。",
    situations=["在泰国生有子女、父亲为外国人的未婚夫妇",
                "要求先办理泰国认领，才会为子女办理登记的使馆",
                "母亲同意，而父亲希望全程有人安排的情形",
                "父亲的亲子关系或权利存在争议",
                "计划移居国外、需要把文件备齐的家庭"],
    reviewTitle="流程包括哪些内容",
    reviewIntro="我们先确认适用的途径，然后准备每一步。",
    cards=[("适用哪条途径", "凭必要同意办理登记，或向法院提出申请，取决于子女的年龄、母亲是否同意及案件事实。"),
           ("申请书与证据", "准备申请书，收集出生证明、父母的文件及译文。"),
           ("法院开庭", "出庭，父母通常需要出庭的次数，以及哪些步骤可由代表办理。"),
           ("登记与证明", "在县政府登记结果，并取得认领记录（Kor Ror 11）。"),
           ("使馆与护照", "如何向您的使馆出示结果，用于民事登记和子女护照。"),
           ("相关事项", "姓氏、亲权与监护、抚养费，以及父母日后分开时的安排。")],
    noEyebrow="开始之前",
    noTitle="了解适用于您的途径",
    noText="合适的途径取决于母亲是否同意、子女是否已到可以征求意见的年龄，以及您的使馆有何要求。我们会先确认这些，避免您向错误的地方提交或遗漏文件。我们也会说明这一程序不决定哪些事项：例如国籍，取决于您本国的规定。",
    fallbackTitle="我们首先确认的事项",
    fallbacks=["子女的年龄及出生登记的地点",
               "母亲是否同意，以及她能否到场",
               "您的使馆接受哪些证明",
               "是否存在亲子关系或监护权争议",
               "您的时间安排，例如计划移居国外"],
    stages=[("途径与文件核查：", "确认适用的途径以及所需文件。"),
            ("提交申请或登记：", "准备并提交申请或登记。"),
            ("法院开庭：", "在少年及家事法院代表您出庭。"),
            ("登记与证明：", "在县政府办理登记并取得认领记录。"),
            ("使馆跟进：", "协助向您的使馆提交文件。")],
    faq=[("出生证明上有我的名字，我就是法律上的父亲吗？", "不一定。未与母亲结婚的父亲通常需要办理认领，其与子女的关系才会得到正式承认。"),
         ("认领可以不上法院吗？", "在某些情况下可以，即凭必要的同意在县政府办理登记。如果缺少同意，或子女年幼无法表示同意，通常需要法院裁定。我们会确认适用哪一种。"),
         ("母亲需要到场吗？", "通常需要母亲的同意，并且一般会要求她出面或确认，但具体要求取决于所走的途径和法院。"),
         ("需要多长时间？", "取决于途径、法院的日程和文件。我们会在了解您的情况后给出时间估计。"),
         ("这会让我的孩子获得我的国籍吗？", "不会。国籍取决于您本国的法律。认领通常是您的使馆在为孩子办理登记之前要求的一个步骤。")],
)

PAGE = dict(
    slug='child-legitimation-thailand',
    heroimg='family-lawyer.webp',
    practice='family-law-services',
    icons=['ti-route', 'ti-file-text', 'ti-gavel', 'ti-certificate', 'ti-world', 'ti-heart-handshake'],
    related=['family-law-services', 'legal-documents-services', 'chonburi-wills-estate-planning', 'pattaya-law-office'],
    topic='family',
    C=C,
)
